-- Z1-Datenbankschema (Struktur, KEINE Daten) - generiert aus der Live-DB, read-only.
-- DBRELEASE 296. Alle Spalten varchar (Z1-Konvention). Keine deklarierten Foreign Keys.
-- Beziehungen laufen implizit ueber Spaltennamen (PATNR, LFD*, MDID, LEBID, ADRID*).

CREATE TABLE [ABEFUND] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LFDABEFUND] varchar(3) ,
  [BEFUND] varchar(72) ,
  [CARIESFLAECHEN] varchar(72) ,
  [FLGFLAECHEN] varchar(72) ,
  [INLAYFLAECHEN] varchar(72) ,
  [AFLGFLAECHEN] varchar(72) ,
  [WFKANAELE] varchar(72) ,
  [WKKANAELE] varchar(72) ,
  [VITAL] varchar(72) ,
  [ROE] varchar(72) ,
  [P] varchar(72) ,
  [CP] varchar(72) ,
  [KRONENART] varchar(72) ,
  [IMPLANTATART] varchar(72) ,
  [ZAHNSTEIN] varchar(72) ,
  [API] varchar(32) ,
  [PBI] varchar(32) ,
  [MUNDKRANKHEIT] varchar(1) ,
  [SONSTIGERBEFUND] varchar(40) ,
  [PSI] varchar(12) ,
  [PRA] varchar(40) ,
  [ZUSATZ1] varchar(72) ,
  [ZUSATZ2] varchar(72) ,
  [ZUSATZ3] varchar(72) ,
  [ZUSATZ4] varchar(72) ,
  [ZUSATZ5] varchar(72) ,
  [LAGEMES] varchar(72) ,
  [LAGEOCC] varchar(72) ,
  [LAGEDIS] varchar(72) ,
  [LAGEVES] varchar(72) ,
  [LAGELIN] varchar(72) ,
  [LAGEZHA] varchar(72) ,
  CONSTRAINT [PK_ABEFUND] PRIMARY KEY ([PATNR], [LFDABEFUND])
);

CREATE TABLE [ADR] (
  [RINFO] varchar(34) ,
  [ADRID] varchar(6) ,
  [ABDATUM] varchar(8) ,
  [ART] varchar(1) ,
  [SUBART] varchar(1) ,
  [TITEL] varchar(28) ,
  [VORNAME] varchar(45) ,
  [KYVORNAME] varchar(45) ,
  [NAMENSZUSATZ] varchar(15) ,
  [NAME] varchar(45) ,
  [KYNAME] varchar(45) ,
  [FRUEHERENAMEN] varchar(84) ,
  [FENSTERZEILE1] varchar(50) ,
  [FENSTERZEILE2] varchar(50) ,
  [FENSTERZEILE3] varchar(50) ,
  [STR] varchar(50) ,
  [ANSCHRIFTENZUSATZ] varchar(40) ,
  [LANDKUERZEL] varchar(3) ,
  [PLZ] varchar(20) ,
  [ORT] varchar(50) ,
  [SEX] varchar(1) ,
  [BRIEFANREDE] varchar(80) ,
  [INTROTB] varchar(8) ,
  [KZVABRNR] varchar(10) ,
  [KVABRNR] varchar(10) ,
  [BSULANR] varchar(18) ,
  [ENTFERNUNG] varchar(7) ,
  [TELEFON1] varchar(102) ,
  [TELEFON2] varchar(102) ,
  [TELEFON3] varchar(102) ,
  [TELEFON4] varchar(102) ,
  [TELEFON5] varchar(102) ,
  [TELEFON6] varchar(102) ,
  [TELEFON7] varchar(102) ,
  [GEBDATUM] varchar(8) ,
  [GEBORT] varchar(50) ,
  [ANSPRECHPARTNER] varchar(30) ,
  [BERUF] varchar(50) ,
  [INSTITUT] varchar(50) ,
  [BLZ] varchar(20) ,
  [KONTONR] varchar(20) ,
  [BIC] varchar(20) ,
  [IBAN] varchar(40) ,
  [KONTOINHABER] varchar(70) ,
  [KONTOGUELTIGAB] varchar(8) ,
  [KONTOSONST] varchar(100) ,
  [LASTSCHRIFTART] varchar(1) ,
  [LASTLASTSCHRIFT] varchar(8) ,
  [KTO] varchar(6) ,
  [LASTEINVFOTO] varchar(8) ,
  [SECUREMAIL] varchar(254) ,
  [ADRSONST1] varchar(20) ,
  [VORSATZWORT] varchar(20) ,
  [ZANR] varchar(9) ,
  CONSTRAINT [PK_ADR] PRIMARY KEY ([ADRID], [ABDATUM])
);
CREATE INDEX [K2ADR] ON [ADR] ([KYNAME], [KYVORNAME], [ABDATUM]);
CREATE INDEX [K3ADR] ON [ADR] ([ART], [KYNAME], [KYVORNAME], [ABDATUM]);

CREATE TABLE [ARCHIV] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LFDARCHIV] varchar(4) ,
  [OBJEKTART] varchar(1) ,
  [OBJEKTDATUM] varchar(8) ,
  [OBJEKTBESCHREIBUNG] varchar(50) ,
  [EXTERNOBJEKTART] varchar(10) ,
  [BVS] varchar(30) ,
  [MMOID] varchar(200) ,
  [EXTERNARCHIVID] varchar(20) ,
  [PRAXISID] varchar(3) ,
  [EXTERNPRAXISID] varchar(5) ,
  [EPAUNIQUEID] varchar(64) ,
  CONSTRAINT [PK_ARCHIV] PRIMARY KEY ([PATNR], [LFDARCHIV])
);
CREATE UNIQUE INDEX [K2ARCHIV] ON [ARCHIV] ([PATNR], [OBJEKTART], [OBJEKTDATUM], [LFDARCHIV]);

CREATE TABLE [ARZNEIMITTEL] (
  [RINFO] varchar(34) ,
  [LFDARZNEIMITTEL] varchar(4) ,
  [ARZNEIMITTELNAME] varchar(50) ,
  [KYARZNEIMITTELNAME] varchar(50) ,
  [PHARMAZENTRALNR] varchar(10) ,
  [KYPHARMAZENTRALNR] varchar(10) ,
  [DARREICHUNGSFORM] varchar(3) ,
  [MENGE] varchar(15) ,
  [MENGEEINHEIT] varchar(18) ,
  [NORMGROESSE] varchar(1) ,
  [DOSIERUNG] varchar(254) ,
  [WIRKSTOFF1] varchar(95) ,
  [WIRKSTOFF2] varchar(95) ,
  [WIRKSTOFF3] varchar(95) ,
  [BEMERKUNG] varchar(60) ,
  CONSTRAINT [PK_ARZNEIMITTEL] PRIMARY KEY ([LFDARZNEIMITTEL])
);
CREATE INDEX [K2ARZNEIMITTEL] ON [ARZNEIMITTEL] ([KYARZNEIMITTELNAME]);
CREATE INDEX [K3ARZNEIMITTEL] ON [ARZNEIMITTEL] ([KYPHARMAZENTRALNR]);

CREATE TABLE [AUFGABEN] (
  [RINFO] varchar(34) ,
  [AUFGABENID] varchar(10) ,
  [VALID] varchar(1) ,
  [KURZTEXT] varchar(50) ,
  [KATEGORIE] varchar(1) ,
  [PID] varchar(3) ,
  [WORKSTATION] varchar(3) ,
  [PRAXISID] varchar(3) ,
  [PID2] varchar(3) ,
  [PID3] varchar(3) ,
  [TEAMRELEVANT] varchar(1) ,
  [TEAMLFDNR] varchar(5) ,
  [QMRELEVANT] varchar(1) ,
  [QMKATEGORIE] varchar(1) ,
  [QMTITEL] varchar(254) ,
  [QMLINKZIEL] varchar(254) ,
  [PRIO] varchar(1) ,
  [DATUM] varchar(8) ,
  [UHRZEIT] varchar(4) ,
  [INTERVALL] varchar(2) ,
  [INTERVALLART] varchar(1) ,
  [WOCHENTAGE] varchar(1) ,
  [BISDATUM] varchar(8) ,
  [WARNINTERVALL] varchar(2) ,
  [WARNDATUM] varchar(8) ,
  [GERAETEID] varchar(5) ,
  [VORLAGE] varchar(1) ,
  [PATNR] varchar(10) ,
  [CREATEDATUM] varchar(8) ,
  CONSTRAINT [PK_AUFGABEN] PRIMARY KEY ([AUFGABENID])
);
CREATE INDEX [K2AUFGABEN] ON [AUFGABEN] ([PRIO], [DATUM], [UHRZEIT], [GERAETEID], [AUFGABENID]);
CREATE INDEX [K3AUFGABEN] ON [AUFGABEN] ([KURZTEXT], [AUFGABENID]);

CREATE TABLE [BANKEN] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [LFDBANK] varchar(2) ,
  [ADRID] varchar(6) ,
  [ECINDEX] varchar(1) ,
  [VORLAUFERST] varchar(2) ,
  [VORLAUFFOLGE] varchar(2) ,
  CONSTRAINT [PK_BANKEN] PRIMARY KEY ([MDID], [LFDBANK])
);

CREATE TABLE [BANKOUT] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [KREDITORART] varchar(1) ,
  [KREDITORID] varchar(10) ,
  [EMPFAENGER] varchar(30) ,
  [INSTITUT] varchar(50) ,
  [BLZ] varchar(20) ,
  [KONTONR] varchar(20) ,
  [BIC] varchar(20) ,
  [IBAN] varchar(40) ,
  [UEFORMART] varchar(1) ,
  [LFDBANKOUT] varchar(5) ,
  [LFDBANKOUTP] varchar(5) ,
  [BUCHUNGSART] varchar(1) ,
  [LFDFAKT] varchar(5) ,
  [LFDBANK] varchar(2) ,
  [BANKOUTDATUM] varchar(8) ,
  [AUSGEFUEHRT] varchar(8) ,
  [FAKTBETRAG] varchar(10) ,
  [FAKTUST] varchar(10) ,
  [CASHBETRAG] varchar(10) ,
  [CASHUST] varchar(10) ,
  [SKONTO] varchar(5) ,
  [STORNIERT] varchar(1) ,
  [Z1INTERN] varchar(30) ,
  [KTO] varchar(6) ,
  [BELEG] varchar(8) ,
  [FTRANSFERED] varchar(1) ,
  [BUCHUNGSTEXT] varchar(60) ,
  [BEMERKUNG] varchar(50) ,
  [RATENMODUS] varchar(1) ,
  [ZAHLTAG] varchar(8) ,
  [ANZAHLUNGSBETRAG] varchar(9) ,
  [RATENBETRAG] varchar(9) ,
  [ERSTERATE] varchar(8) ,
  [LETZTERATE] varchar(8) ,
  [ANZAHLRATEN] varchar(3) ,
  [LFDRATE] varchar(3) ,
  CONSTRAINT [PK_BANKOUT] PRIMARY KEY ([MDID], [LFDBANKOUT])
);
CREATE UNIQUE INDEX [K2BANKOUT] ON [BANKOUT] ([MDID], [BANKOUTDATUM], [KREDITORART], [KREDITORID], [LFDBANKOUT]);
CREATE UNIQUE INDEX [K3BANKOUT] ON [BANKOUT] ([MDID], [KREDITORART], [KREDITORID], [LFDBANKOUT]);

CREATE TABLE [BEH] (
  [RINFO] varchar(34) ,
  [CINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LEBID] varchar(3) ,
  [PID] varchar(3) ,
  [DATUM] varchar(8) ,
  [BEHSESSION] varchar(1) ,
  [LFDSESSIONENTRY] varchar(4) ,
  [ZAEHNE] varchar(18) ,
  [ANZAHL] varchar(6) ,
  [ENDGEWICHT] varchar(6) ,
  [LSTIN] varchar(6) ,
  [LSTNR] varchar(6) ,
  [KYLSTNR] varchar(6) ,
  [GOART] varchar(1) ,
  [LABPREISGRUPPE] varchar(1) ,
  [FAKTOR] varchar(6) ,
  [DMBETRAG] varchar(11) ,
  [USTKEY] varchar(1) ,
  [UST] varchar(11) ,
  [FLGLAGEN] varchar(6) ,
  [ENTFERNUNG] varchar(7) ,
  [UHRZEIT] varchar(4) ,
  [DTABEGRUENDUNG] varchar(1) ,
  [BEHTEXTART] varchar(1) ,
  [ICDCODE] varchar(5) ,
  [ICDCODEAPPENDIX] varchar(2) ,
  [ICDNOTATIONSKZ] varchar(1) ,
  [MEDIKAMENT] varchar(10) ,
  [BEHTEXT] varchar(60) ,
  [UEBERSTIMMT] varchar(1) ,
  [ABRMERKMAL] varchar(1) ,
  [LFDPATBILL] varchar(5) ,
  [PRIVAT] varchar(1) ,
  [MATBUCHUNG] varchar(1) ,
  [BEFUNDART] varchar(1) ,
  [LFDBEFUND] varchar(3) ,
  [LFDPLAN] varchar(3) ,
  [LFDLBLOCK] varchar(3) ,
  [LFDLBLOCKENTRY] varchar(3) ,
  [LFDARCHIV] varchar(4) ,
  [BEHSONST1] varchar(254) ,
  CONSTRAINT [PK_BEH] PRIMARY KEY ([PATNR], [DATUM], [BEHSESSION], [LFDSESSIONENTRY])
);
CREATE UNIQUE INDEX [K2BEH] ON [BEH] ([LEBID], [DATUM], [BEHSESSION], [LFDSESSIONENTRY], [PATNR], [GOART], [KYLSTNR]);
CREATE UNIQUE INDEX [K3BEH] ON [BEH] ([LEBID], [GOART], [KYLSTNR], [DATUM], [BEHSESSION], [LFDSESSIONENTRY], [PATNR]);

CREATE TABLE [BILL] (
  [RINFO] varchar(34) ,
  [CINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [PATNR] varchar(10) ,
  [LFDPATBILL] varchar(5) ,
  [ABRART] varchar(1) ,
  [ABRPERDTA] varchar(1) ,
  [GLFDPATVD] varchar(3) ,
  [GKTRAEGER] varchar(1) ,
  [GFID] varchar(4) ,
  [GABRWUNSCHDATUM] varchar(8) ,
  [GLFDFAKT] varchar(5) ,
  [GABRDATUM] varchar(8) ,
  [SFID] varchar(4) ,
  [SABRWUNSCHDATUM] varchar(8) ,
  [SLFDFAKT] varchar(5) ,
  [SABRDATUM] varchar(8) ,
  [PLFDPATVD] varchar(3) ,
  [PKTRAEGER] varchar(1) ,
  [PFID] varchar(4) ,
  [PABRWUNSCHDATUM] varchar(8) ,
  [PLFDFAKT] varchar(5) ,
  [PABRDATUM] varchar(8) ,
  [LFDHPLAN] varchar(3) ,
  [BETRAG] varchar(10) ,
  [CHECKSTATUS] varchar(80) ,
  [PATNAME] varchar(28) ,
  [PATVORNAME] varchar(28) ,
  [PATGEBDATUM] varchar(8) ,
  [Z1KASKUERZEL] varchar(10) ,
  [VONBEHDATUM] varchar(8) ,
  [BISBEHDATUM] varchar(8) ,
  [KKGINFO] varchar(4) ,
  [BRZPAKET] varchar(1) ,
  CONSTRAINT [PK_BILL] PRIMARY KEY ([PATNR], [LFDPATBILL])
);
CREATE UNIQUE INDEX [K2BILL] ON [BILL] ([MDID], [PATNR], [LFDPATBILL]);

CREATE TABLE [BILLRULE] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [KASKUERZEL] varchar(10) ,
  [PATNR] varchar(10) ,
  [RULEART] varchar(1) ,
  [ABRART] varchar(1) ,
  [ABRPERDTA] varchar(1) ,
  [GKTRAEGER] varchar(1) ,
  [GFID] varchar(4) ,
  [SFID] varchar(4) ,
  [PKTRAEGER] varchar(1) ,
  [PFID] varchar(4) ,
  CONSTRAINT [PK_BILLRULE] PRIMARY KEY ([MDID], [PATNR], [KASKUERZEL], [RULEART])
);

CREATE TABLE [BKTKASSEN] (
  [RINFO] varchar(34) ,
  [BKTKASNR] varchar(11) ,
  [KYBKTKASNR] varchar(11) ,
  [VKNR] varchar(5) ,
  [FUSIONSVKNR] varchar(5) ,
  [BKTKASSENART] varchar(2) ,
  [KASSENGRUPPE] varchar(1) ,
  [AUSSCHLUSSKV] varchar(60) ,
  [VERTRAGSKV] varchar(2) ,
  [ABRECHNUNGSIK] varchar(1) ,
  [BKTVKNRGUELTIGBIS] varchar(8) ,
  [BKTVKNRGUELTIGAB] varchar(8) ,
  [KVKKASNRGUELTIGBIS] varchar(8) ,
  [KVKKASNRGUELTIGAB] varchar(8) ,
  [BKTABKGUELTIGBIS] varchar(8) ,
  [BKTABKGUELTIGAB] varchar(8) ,
  [EXISTENZBEENDIGUNG] varchar(1) ,
  [LETZTESQUARTAL] varchar(5) ,
  [BKTKASNAME] varchar(30) ,
  [BKTPLZ] varchar(8) ,
  [BKTORT] varchar(30) ,
  [BKTSTR] varchar(60) ,
  [BKTPLZ2] varchar(8) ,
  [BKTORT2] varchar(30) ,
  [BKTPOSTFACH] varchar(60) ,
  [BKTKASSUCHNAME] varchar(60) ,
  [KYBKTKASSUCHNAME] varchar(60) ,
  [BKTKASKUERZEL] varchar(16) ,
  [KYBKTKASKUERZEL] varchar(16) ,
  [TEMPORAER] varchar(1) ,
  CONSTRAINT [PK_BKTKASSEN] PRIMARY KEY ([KYBKTKASNR])
);
CREATE INDEX [K2BKTKASSEN] ON [BKTKASSEN] ([VKNR]);
CREATE INDEX [K3BKTKASSEN] ON [BKTKASSEN] ([KYBKTKASKUERZEL]);
CREATE INDEX [K4BKTKASSEN] ON [BKTKASSEN] ([KYBKTKASSUCHNAME]);

CREATE TABLE [BKTORT] (
  [RINFO] varchar(34) ,
  [VKNR] varchar(5) ,
  [KYVKNR] varchar(5) ,
  [SUCHORT] varchar(30) ,
  [KYSUCHORT] varchar(30) ,
  CONSTRAINT [PK_BKTORT] PRIMARY KEY ([KYVKNR], [KYSUCHORT])
);
CREATE UNIQUE INDEX [K2BKTORT] ON [BKTORT] ([KYSUCHORT], [KYVKNR]);

CREATE TABLE [BKVKASSEN] (
  [RINFO] varchar(34) ,
  [BKVKASNR] varchar(12) ,
  [KYBKVKASNR] varchar(12) ,
  [KASSENART] varchar(1) ,
  [KASSENBLOCK] varchar(1) ,
  [LARTABR] varchar(8) ,
  [BKVKASNAME] varchar(30) ,
  [KYBKVKASNAME] varchar(30) ,
  [PLZ] varchar(6) ,
  [ORT] varchar(30) ,
  [STR] varchar(30) ,
  [TELEFON] varchar(16) ,
  [TELEFAX] varchar(16) ,
  [KVKKASNR] varchar(7) ,
  [KYKVKKASNR] varchar(7) ,
  [BKVKASKUERZEL] varchar(16) ,
  [KYBKVKASKUERZEL] varchar(16) ,
  [EBZIK] varchar(9) ,
  CONSTRAINT [PK_BKVKASSEN] PRIMARY KEY ([KYBKVKASNR])
);
CREATE INDEX [K2BKVKASSEN] ON [BKVKASSEN] ([KYKVKKASNR]);
CREATE INDEX [K3BKVKASSEN] ON [BKVKASSEN] ([KYBKVKASKUERZEL]);
CREATE INDEX [K4BKVKASSEN] ON [BKVKASSEN] ([KYBKVKASNAME]);

CREATE TABLE [BMBEH] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LEBID] varchar(3) ,
  [DATUM] varchar(8) ,
  [BEHSESSION] varchar(1) ,
  [LFDSESSIONENTRY] varchar(4) ,
  [ZAEHNE] varchar(18) ,
  [ANZAHL] varchar(6) ,
  [LSTNR] varchar(6) ,
  [KYLSTNR] varchar(6) ,
  [GOART] varchar(1) ,
  [FAKTOR] varchar(6) ,
  [DMBETRAG] varchar(11) ,
  [FLGLAGEN] varchar(6) ,
  [BEHTEXTART] varchar(1) ,
  [BEHTEXT] varchar(60) ,
  [LFDPATBILL] varchar(5) ,
  [ABRMERKMAL] varchar(1) ,
  [BEFUNDART] varchar(1) ,
  [LFDBEFUND] varchar(3) ,
  CONSTRAINT [PK_BMBEH] PRIMARY KEY ([PATNR], [DATUM], [BEHSESSION], [LFDSESSIONENTRY])
);

CREATE TABLE [CASH] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [PATNR] varchar(10) ,
  [LFDFAKT] varchar(5) ,
  [LFDCASH] varchar(5) ,
  [LFDZAHLUNG] varchar(3) ,
  [LFDCASHPAY] varchar(10) ,
  [CASHDATUM] varchar(8) ,
  [BUCHUNGSART] varchar(1) ,
  [ZAHLUNGSWEG] varchar(1) ,
  [LFDBANK] varchar(2) ,
  [BETRAG] varchar(10) ,
  [STORNIERT] varchar(1) ,
  [PIDPAY] varchar(3) ,
  [PIDSTORNO] varchar(3) ,
  [DATUMSTORNO] varchar(8) ,
  [RATENMODUS] varchar(1) ,
  [ANZAHLUNGSBETRAG] varchar(9) ,
  [RATENBETRAG] varchar(9) ,
  [KTO] varchar(6) ,
  [BELEG] varchar(8) ,
  [FTRANSFERED] varchar(1) ,
  [BUCHUNGSTEXT] varchar(60) ,
  [Z1CASHINTERN] varchar(60) ,
  [Z1CASHINTERN2] varchar(60) ,
  [PATNAME] varchar(28) ,
  [PATVORNAME] varchar(28) ,
  [PATGEBDATUM] varchar(8) ,
  [Z1KASKUERZEL] varchar(10) ,
  [BEMERKUNG] varchar(30) ,
  [BUCHUNGSDATUM] varchar(8) ,
  CONSTRAINT [PK_CASH] PRIMARY KEY ([MDID], [PATNR], [LFDFAKT], [LFDCASH])
);
CREATE UNIQUE INDEX [K2CASH] ON [CASH] ([MDID], [CASHDATUM], [PATNR], [LFDFAKT], [LFDCASH]);

CREATE TABLE [CASHPAY] (
  [RINFO] varchar(34) ,
  [LFDCASHPAY] varchar(10) ,
  [MDID] varchar(2) ,
  [PATNR] varchar(10) ,
  [LFDBANK] varchar(2) ,
  [HERKUNFT] varchar(3) ,
  [SALDO] varchar(13) ,
  [AGBLZ] varchar(12) ,
  [AGKTO] varchar(15) ,
  [AGNAME] varchar(80) ,
  [OCMTBETR] varchar(10) ,
  [BETRAG] varchar(10) ,
  [EINNAHME] varchar(1) ,
  [BETRZUGETEILT] varchar(10) ,
  [BETRAUSGLEICH] varchar(10) ,
  [STORNIERT] varchar(1) ,
  [TEXTSCHLUESSEL] varchar(40) ,
  [SPEZIAL1] varchar(254) ,
  [SPEZIAL2] varchar(254) ,
  [SPEZIAL3] varchar(254) ,
  [BUCHDATUM] varchar(8) ,
  [WERTDATUM] varchar(8) ,
  [PRIMANOTA] varchar(8) ,
  [KATEGORIE] varchar(40) ,
  [UNTERKATEGORIE] varchar(40) ,
  [KOSTENSTELLE] varchar(40) ,
  [BUCHUNGSTEXT] varchar(60) ,
  CONSTRAINT [PK_CASHPAY] PRIMARY KEY ([LFDCASHPAY])
);

CREATE TABLE [CMD] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LFDCMD] varchar(3) ,
  [KATEGORIE] varchar(3) ,
  [LFDBEFUND] varchar(3) ,
  [LFDFREITEXT] varchar(3) ,
  [FELDID] varchar(30) ,
  [KYFELDID] varchar(30) ,
  [LFDTEXT] varchar(3) ,
  [TXT] varchar(80) ,
  [DATUM] varchar(8) ,
  [LEBID] varchar(3) ,
  [FLAG1] varchar(1) ,
  [FLAG2] varchar(1) ,
  [SELECT1] varchar(50) ,
  [SELECT2] varchar(50) ,
  [TXT1] varchar(80) ,
  [TXT2] varchar(80) ,
  [TXT3] varchar(80) ,
  [TXT4] varchar(80) ,
  CONSTRAINT [PK_CMD] PRIMARY KEY ([PATNR], [LFDCMD], [KATEGORIE], [LFDBEFUND], [LFDFREITEXT], [KYFELDID], [LFDTEXT])
);

CREATE TABLE [DATEVONLINELOG] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [LFDLOG] varchar(9) ,
  [ZEITSTEMPEL] varchar(14) ,
  [ANFRAGEART] varchar(1) ,
  [HTTPVERB] varchar(1) ,
  [ANFRAGEURL] varchar(254) ,
  [HTTPRESPONSECODE] varchar(3) ,
  [HTTPRESPONSETEXT] varchar(max) ,
  [HTTPRESPONSEHEADER] varchar(max) ,
  [HTTPREQUESTBODY] varchar(max) ,
  [HTTPREQUESTHEADER] varchar(max) ,
  CONSTRAINT [PK_DATEVONLINELOG] PRIMARY KEY ([MDID], [LFDLOG])
);
CREATE UNIQUE INDEX [K2DATEVONLINELOG] ON [DATEVONLINELOG] ([MDID], [ZEITSTEMPEL], [LFDLOG]);

CREATE TABLE [DATEVPAKET] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [PAKETNR] varchar(9) ,
  [HERKUNFT] varchar(1) ,
  [ANLAGEDATUM] varchar(8) ,
  [UPLOADDATUM] varchar(8) ,
  [JOBID] varchar(36) ,
  [EXTFID] varchar(36) ,
  [STATUS] varchar(1) ,
  [STATUSINFO] varchar(max) ,
  [STAPELBESCHRIFTUNG] varchar(64) ,
  CONSTRAINT [PK_DATEVPAKET] PRIMARY KEY ([MDID], [PAKETNR])
);
CREATE UNIQUE INDEX [K2DATEVPAKET] ON [DATEVPAKET] ([MDID], [ANLAGEDATUM], [PAKETNR]);

CREATE TABLE [DATEVPAKETENTRY] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [PAKETNR] varchar(9) ,
  [PATNR] varchar(10) ,
  [LFDFAKT] varchar(5) ,
  [LFDENTRY] varchar(2) ,
  [ENTRYTYP] varchar(1) ,
  [LFDARCHIV] varchar(4) ,
  [FILEPATH] varchar(254) ,
  [ENTRYUUID] varchar(36) ,
  [UPLOADDATUM] varchar(8) ,
  [PREVPAKETNR] varchar(9) ,
  [DATEVKONTIERUNG] varchar(max) ,
  CONSTRAINT [PK_DATEVPAKETENTRY] PRIMARY KEY ([MDID], [PAKETNR], [PATNR], [LFDFAKT], [LFDENTRY])
);

CREATE TABLE [DOKUMENT] (
  [RINFO] varchar(34) ,
  [DOKUMENTART] varchar(1) ,
  [DOKUMENTKEY] varchar(36) ,
  [LFDDOKUMENT] varchar(3) ,
  [KATEGORIE] varchar(1) ,
  [TITEL] varchar(254) ,
  [PFAD] varchar(254) ,
  [EPAUNIQUEID] varchar(64) ,
  CONSTRAINT [PK_DOKUMENT] PRIMARY KEY ([DOKUMENTART], [DOKUMENTKEY], [LFDDOKUMENT])
);

CREATE TABLE [EBEFUND] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LFDEBEFUND] varchar(3) ,
  [ZAHNNR] varchar(2) ,
  [BEHABSCHLUSS] varchar(8) ,
  [AKANZ] varchar(1) ,
  [AKGEKRUEMMT] varchar(5) ,
  [AKRBEF] varchar(10) ,
  [AAPEX] varchar(10) ,
  [ASONDIERUNG] varchar(20) ,
  [AKBEFUND] varchar(10) ,
  [APARODONT] varchar(10) ,
  [APULPA] varchar(10) ,
  [ATREPANATION] varchar(10) ,
  [AINDIKATION] varchar(10) ,
  [AAUFKLAERUNG] varchar(8) ,
  [BVORBEREITUNG] varchar(10) ,
  [BRISIKO] varchar(10) ,
  [BRECALL] varchar(1) ,
  [BLOKALISATION] varchar(24) ,
  [BENDOML] varchar(18) ,
  [BINSTRUMENT] varchar(24) ,
  [BISO] varchar(24) ,
  [BREFERENZ] varchar(24) ,
  [BAL] varchar(18) ,
  [BKAUF] varchar(24) ,
  [BKL] varchar(18) ,
  [BMETHODE] varchar(24) ,
  [BSPUELUNG] varchar(24) ,
  [BMEDEINL] varchar(150) ,
  [BFUELLMAT] varchar(24) ,
  [BFL] varchar(18) ,
  [BFUELLTECH] varchar(24) ,
  [BSPUELUNG2] varchar(24) ,
  [BSPUELUNG3] varchar(24) ,
  [BMEDEINL2] varchar(150) ,
  [BRADIOL] varchar(18) ,
  [BPATENT] varchar(18) ,
  [BROEMESSINST] varchar(24) ,
  [BROEMESSL] varchar(18) ,
  [BAUFBEREITUNG] varchar(24) ,
  [BPUI] varchar(6) ,
  [BLAI] varchar(6) ,
  [BSEALER] varchar(24) ,
  [BUEBERPRESS] varchar(6) ,
  CONSTRAINT [PK_EBEFUND] PRIMARY KEY ([PATNR], [LFDEBEFUND], [ZAHNNR])
);

CREATE TABLE [EBZ] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LFDPLAN] varchar(3) ,
  [LFDNR] varchar(3) ,
  [MDID] varchar(2) ,
  [DOKART] varchar(1) ,
  [STATUS] varchar(1) ,
  [ERSTELLDATUM] varchar(8) ,
  [SIGNATURDATUM] varchar(8) ,
  [VERSANDDATUM] varchar(8) ,
  [ERHALTDATUM] varchar(8) ,
  [ZUGESTELLT] varchar(1) ,
  [DATEINAME] varchar(100) ,
  [DATEINAMEECHT] varchar(64) ,
  CONSTRAINT [PK_EBZ] PRIMARY KEY ([PATNR], [LFDPLAN], [LFDNR])
);

CREATE TABLE [EINWILLIGUNG] (
  [RINFO] varchar(34) ,
  [PATNRADRID] varchar(10) ,
  [MDID] varchar(2) ,
  [EINWILLIGUNGART] varchar(2) ,
  [DRUCKDATUM] varchar(8) ,
  [UNTERSCHRIFTDATUM] varchar(8) ,
  [UNTERSCHRIFTART] varchar(1) ,
  [WIDERRUFDATUM] varchar(8) ,
  [BEMERKUNG] varchar(60) ,
  [LFDARCHIV] varchar(4) ,
  [DOKUMENTKEY] varchar(36) ,
  [LFDDOKUMENT] varchar(3) ,
  [TELEFONDATUM] varchar(14) ,
  [TELEFONPID] varchar(3) ,
  [NURTELEFON] varchar(1) ,
  CONSTRAINT [PK_EINWILLIGUNG] PRIMARY KEY ([PATNRADRID], [MDID], [EINWILLIGUNGART], [DRUCKDATUM])
);

CREATE TABLE [ELABOR] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LFDPLAN] varchar(3) ,
  [LFDLBLOCK] varchar(3) ,
  [LFDELABOR] varchar(3) ,
  [ELABORART] varchar(1) ,
  [TODO] varchar(1) ,
  [MESSAGEID] varchar(254) ,
  [REPLYTOMESSAGEID] varchar(254) ,
  [ERSTELLDATUM] varchar(8) ,
  [SIGNATURDATUM] varchar(8) ,
  [VERSANDDATUM] varchar(8) ,
  [ERHALTDATUM] varchar(8) ,
  CONSTRAINT [PK_ELABOR] PRIMARY KEY ([PATNR], [LFDPLAN], [LFDLBLOCK], [LFDELABOR])
);
CREATE UNIQUE INDEX [K2ELABOR] ON [ELABOR] ([MESSAGEID]);
CREATE INDEX [K3ELABOR] ON [ELABOR] ([REPLYTOMESSAGEID]);

CREATE TABLE [EPADOCUMENT] (
  [RINFO] varchar(34) ,
  [UNIQUEID] varchar(64) ,
  [ENTRYUUID] varchar(64) ,
  [PATNR] varchar(10) ,
  [STATUS] varchar(1) ,
  [AUTHOR] varchar(max) ,
  [CLASSCODE] varchar(64) ,
  [COMMENTS] varchar(254) ,
  [CONFIDENTIALITYCODE] varchar(max) ,
  [CREATIONTIME] varchar(20) ,
  [EVENTCODELIST] varchar(max) ,
  [FORMATCODE] varchar(254) ,
  [HASH] varchar(64) ,
  [HFTCODE] varchar(64) ,
  [HOMECOMMUNITYID] varchar(64) ,
  [LANGUAGECODE] varchar(5) ,
  [LEGALAUTHENTICATOR] varchar(max) ,
  [MIMETYPE] varchar(2) ,
  [PATIENTID] varchar(64) ,
  [PRACTICESETTINGCODE] varchar(64) ,
  [REPOSITORYUNIQUEID] varchar(64) ,
  [SERVICESTARTTIME] varchar(20) ,
  [SERVICESTOPTIME] varchar(20) ,
  [SIZE] varchar(10) ,
  [SOURCEPATIENTID] varchar(64) ,
  [SOURCEPATIENTINFO] varchar(max) ,
  [TITLE] varchar(254) ,
  [TYPCODE] varchar(64) ,
  [URI] varchar(254) ,
  [FOLDERUUID] varchar(64) ,
  [VERSION] varchar(10) ,
  CONSTRAINT [PK_EPADOCUMENT] PRIMARY KEY ([UNIQUEID])
);
CREATE UNIQUE INDEX [K2EPADOCUMENT] ON [EPADOCUMENT] ([ENTRYUUID]);

CREATE TABLE [ETSSTERMIN] (
  [RINFO] varchar(34) ,
  [ETSSCODE] varchar(12) ,
  [LFDNR] varchar(3) ,
  [MDID] varchar(2) ,
  [PATNR] varchar(10) ,
  [PATPREFIX] varchar(20) ,
  [PATNAME] varchar(45) ,
  [PATSUFFIX] varchar(20) ,
  [PATVORNAME] varchar(45) ,
  [PATGEBDATUM] varchar(8) ,
  [PATSEX] varchar(1) ,
  [PATSTRASSE] varchar(46) ,
  [PATHAUSNR] varchar(9) ,
  [PATORT] varchar(40) ,
  [PATPLZ] varchar(10) ,
  [ERSTVERMITTLUNG] varchar(8) ,
  [PRIORITAET] varchar(1) ,
  [STATUSTSS] varchar(1) ,
  [STATUSZ1] varchar(1) ,
  [STARTDATUM] varchar(8) ,
  [STARTZEIT] varchar(4) ,
  [ENDDATUM] varchar(8) ,
  [ENDZEIT] varchar(4) ,
  [HERKUNFT] varchar(254) ,
  [TELEFON1] varchar(102) ,
  [TELEFON2] varchar(102) ,
  [PATTITEL] varchar(28) ,
  [KOMMENTAR] varchar(254) ,
  CONSTRAINT [PK_ETSSTERMIN] PRIMARY KEY ([ETSSCODE], [LFDNR])
);

CREATE TABLE [FABLAGEENTRY] (
  [RINFO] varchar(34) ,
  [LFDFORMABLAGE] varchar(8) ,
  [LFDFABLAGEENTRY] varchar(2) ,
  [DIAGNOSEN] varchar(254) ,
  [ERGEBNISSE] varchar(254) ,
  [MASSNAHMEN] varchar(254) ,
  [HINWEISE] varchar(254) ,
  [BEFUNDE] varchar(254) ,
  [BEGRUEND] varchar(254) ,
  [FELDINHALT] varchar(254) ,
  CONSTRAINT [PK_FABLAGEENTRY] PRIMARY KEY ([LFDFORMABLAGE], [LFDFABLAGEENTRY])
);

CREATE TABLE [FAKT] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [PATNR] varchar(10) ,
  [LFDFAKT] varchar(5) ,
  [LFDFAKTREF] varchar(5) ,
  [LFDFAKTREFP] varchar(5) ,
  [LFDFAKTREFK] varchar(5) ,
  [FAKTDATUM] varchar(8) ,
  [LFDPATBILL] varchar(5) ,
  [KTRAEGER] varchar(1) ,
  [RART] varchar(4) ,
  [FORTLFDJAHR] varchar(4) ,
  [FORTLFDFAKT] varchar(6) ,
  [EXPECTLFDBANK] varchar(2) ,
  [FORDKTO] varchar(6) ,
  [ERLOESKTO] varchar(6) ,
  [BESCHREIBUNG] varchar(30) ,
  [Z1INTERN] varchar(30) ,
  [BELEG] varchar(8) ,
  [FTRANSFERED] varchar(1) ,
  [BETRAG] varchar(10) ,
  [ZHON] varchar(10) ,
  [ELAB] varchar(10) ,
  [FLAB] varchar(10) ,
  [ELABUST] varchar(10) ,
  [BEGLICHEN] varchar(10) ,
  [AUSGEBUCHT] varchar(10) ,
  [BETRAGK] varchar(10) ,
  [ZHONK] varchar(10) ,
  [ELABK] varchar(10) ,
  [FLABK] varchar(10) ,
  [ELABUSTK] varchar(10) ,
  [HONUST] varchar(44) ,
  [ELAB1USTKEY] varchar(1) ,
  [ELAB1] varchar(10) ,
  [ELAB2USTKEY] varchar(1) ,
  [ELAB2] varchar(10) ,
  [ELAB3USTKEY] varchar(1) ,
  [ELAB3] varchar(10) ,
  [ELAB4USTKEY] varchar(1) ,
  [ELAB4] varchar(10) ,
  [STORNIERT] varchar(1) ,
  [STORNOPID] varchar(3) ,
  [STORNODATUM] varchar(8) ,
  [MAHNSTUFE] varchar(1) ,
  [LASTMAHNDATUM] varchar(8) ,
  [AUFSCHUBDATUM] varchar(8) ,
  [MAHNERLAUBNIS] varchar(1) ,
  [PATNAME] varchar(28) ,
  [PATVORNAME] varchar(28) ,
  [PATGEBDATUM] varchar(8) ,
  [Z1KASKUERZEL] varchar(10) ,
  [BEMERKUNG] varchar(50) ,
  CONSTRAINT [PK_FAKT] PRIMARY KEY ([MDID], [PATNR], [LFDFAKT])
);
CREATE UNIQUE INDEX [K2FAKT] ON [FAKT] ([MDID], [KTRAEGER], [FAKTDATUM], [PATNR], [LFDFAKT]);
CREATE UNIQUE INDEX [K3FAKT] ON [FAKT] ([MDID], [FORTLFDJAHR], [FORTLFDFAKT], [PATNR], [LFDFAKT]);

CREATE TABLE [FBUCHUNG] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [JAHR] varchar(4) ,
  [LFDFBUCHUNG] varchar(5) ,
  [LFDLINK] varchar(5) ,
  [MMDD] varchar(4) ,
  [SOLL] varchar(1) ,
  [BETRAG] varchar(13) ,
  [STORNIERT] varchar(1) ,
  [BKTO] varchar(6) ,
  [GKTO] varchar(6) ,
  [BELEG] varchar(8) ,
  [BUCHUNGSTEXT] varchar(40) ,
  [INTERN] varchar(40) ,
  [PATNR] varchar(10) ,
  [LFDFAKT] varchar(5) ,
  [LFDCASH] varchar(5) ,
  [JOURNALSEITE] varchar(3) ,
  [PID] varchar(3) ,
  [TSEDATA] varchar(max) ,
  CONSTRAINT [PK_FBUCHUNG] PRIMARY KEY ([MDID], [JAHR], [LFDFBUCHUNG])
);
CREATE INDEX [K2FBUCHUNG] ON [FBUCHUNG] ([MDID], [JAHR], [MMDD]);
CREATE INDEX [K3FBUCHUNG] ON [FBUCHUNG] ([MDID], [JAHR], [BKTO], [MMDD]);
CREATE INDEX [K4FBUCHUNG] ON [FBUCHUNG] ([MDID], [JAHR], [GKTO], [MMDD]);
CREATE INDEX [K5FBUCHUNG] ON [FBUCHUNG] ([MDID], [PATNR], [LFDFAKT], [LFDCASH]);

CREATE TABLE [FDIENST] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [KTO] varchar(6) ,
  [DIENSTART] varchar(1) ,
  [LFDDIENST] varchar(3) ,
  [INSMODE] varchar(1) ,
  [ABSTARTDATUM] varchar(8) ,
  [ABINTERVALLART] varchar(1) ,
  [ABINTERVALL] varchar(2) ,
  [ABFIXTAG] varchar(2) ,
  [ABANZAHL] varchar(3) ,
  [ABSPECIAL] varchar(4) ,
  [ABLASTCALLDATUM] varchar(8) ,
  [ABSOLL] varchar(1) ,
  [ABBETRAG] varchar(13) ,
  [ABGKTO] varchar(6) ,
  [ABBELEG] varchar(8) ,
  [BUTEXT] varchar(40) ,
  CONSTRAINT [PK_FDIENST] PRIMARY KEY ([MDID], [KTO], [DIENSTART], [LFDDIENST])
);
CREATE UNIQUE INDEX [K2FDIENST] ON [FDIENST] ([MDID], [DIENSTART], [KTO], [LFDDIENST]);

CREATE TABLE [FILEPOOL] (
  [RINFO] varchar(34) ,
  [CINFO] varchar(34) ,
  [FILEDIR] varchar(254) ,
  [FILENAME] varchar(254) ,
  [FILESIZE] varchar(10) ,
  [FILEDATA] varbinary(max) ,
  CONSTRAINT [PK_FILEPOOL] PRIMARY KEY ([FILEDIR], [FILENAME])
);

CREATE TABLE [FLABS] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [LFDFLAB] varchar(2) ,
  [ADRID] varchar(6) ,
  [KTO] varchar(6) ,
  [ISGLAB] varchar(1) ,
  [SKONTO] varchar(5) ,
  [ANFANG] varchar(11) ,
  [FAVORIT] varchar(1) ,
  [BEZEICHNUNG] varchar(40) ,
  [LIZENZNR] varchar(10) ,
  [BENUTZERNAME] varchar(20) ,
  [PASSWORT] varchar(20) ,
  [ISEXTELAB] varchar(1) ,
  [EXTELABMERKEN] varchar(1) ,
  CONSTRAINT [PK_FLABS] PRIMARY KEY ([MDID], [LFDFLAB])
);

CREATE TABLE [FORMABLAGE] (
  [RINFO] varchar(34) ,
  [LFDFORMABLAGE] varchar(8) ,
  [MDID] varchar(2) ,
  [PATNR] varchar(10) ,
  [DRUCKDATUM] varchar(8) ,
  [FID] varchar(4) ,
  [FORMULARDATUM] varchar(8) ,
  [DRUCKVORLAGE] varchar(10) ,
  [BLANKO] varchar(1) ,
  [EMPFAENGER] varchar(254) ,
  [STEMPEL1BIS6] varchar(254) ,
  [STEMPEL7BIS8] varchar(254) ,
  CONSTRAINT [PK_FORMABLAGE] PRIMARY KEY ([LFDFORMABLAGE])
);
CREATE UNIQUE INDEX [K2FORMABLAGE] ON [FORMABLAGE] ([MDID], [PATNR], [DRUCKDATUM], [FID], [LFDFORMABLAGE]);

CREATE TABLE [FORMULAR] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [FID] varchar(4) ,
  [SYSTEM] varchar(1) ,
  [BESCHREIBUNG] varchar(40) ,
  [PRINTERCLASS] varchar(1) ,
  [SCHACHT] varchar(1) ,
  [FOLGESCHACHT] varchar(1) ,
  [BLANKO] varchar(1) ,
  [DRUCKVORLAGE] varchar(10) ,
  [DVEDITIERBAR] varchar(1) ,
  [SCHRIFTART] varchar(20) ,
  [KNICKMARKER] varchar(1) ,
  [VZTOPMARG] varchar(7) ,
  [VZLEFTMARG] varchar(7) ,
  [DUPLIKATE] varchar(4) ,
  [ASK] varchar(1) ,
  [ARCHIVIEREN] varchar(1) ,
  [MITKOPF] varchar(1) ,
  [KOPFTB] varchar(8) ,
  [RTFKOPF] varchar(64) ,
  [BMPKOPF] varchar(64) ,
  [MITKOPFF] varchar(1) ,
  [KOPFTBF] varchar(8) ,
  [RTFKOPFF] varchar(64) ,
  [BMPKOPFF] varchar(64) ,
  [MITABS] varchar(1) ,
  [ABSTB] varchar(8) ,
  [MITFAKTNR] varchar(1) ,
  [MITRZNR] varchar(1) ,
  [INTROTB] varchar(8) ,
  [BEFUND] varchar(1) ,
  [BEFUNDLEGENDETB] varchar(8) ,
  [SPALTENLEGENDE] varchar(1) ,
  [EUROLEN3] varchar(1) ,
  [LSTTXTMULTILINE] varchar(1) ,
  [MITTEC] varchar(1) ,
  [BONUSINFO] varchar(1) ,
  [MITBEHABSINFO] varchar(1) ,
  [HINWEISTB] varchar(8) ,
  [FUSSTB] varchar(8) ,
  [RTFFUSS] varchar(64) ,
  [BMPFUSS] varchar(64) ,
  [FUSSALLESEITEN] varchar(1) ,
  [MITPATINFO] varchar(1) ,
  [KOSTENGLIEDERUNG] varchar(1) ,
  [AUSGABEWEG] varchar(1) ,
  [TB1] varchar(8) ,
  [TB2] varchar(8) ,
  [TB3] varchar(8) ,
  [TB4] varchar(8) ,
  [TB5] varchar(8) ,
  [ARCHIVDOKU] varchar(1) ,
  [EXPECTLFDBANK] varchar(2) ,
  [FORDKTO] varchar(6) ,
  [ERLOESKTO] varchar(6) ,
  [BRIEFPAPIER] varchar(1) ,
  [SHOWDRIVER] varchar(1) ,
  [FORMULARSONST1] varchar(254) ,
  CONSTRAINT [PK_FORMULAR] PRIMARY KEY ([MDID], [FID])
);

CREATE TABLE [FORMULARLUPB] (
  [RINFO] varchar(34) ,
  [FID] varchar(4) ,
  [MDID] varchar(2) ,
  [LFDWORKSTATION] varchar(3) ,
  [ETIKETTNAME] varchar(254) ,
  [LFDPRINTER] varchar(3) ,
  [BIN1] varchar(5) ,
  [BIN2] varchar(5) ,
  [SPLIT] varchar(1) ,
  [QUEUED] varchar(1) ,
  [USEFORMPARAM] varchar(1) ,
  CONSTRAINT [PK_FORMULARLUPB] PRIMARY KEY ([FID], [MDID], [LFDWORKSTATION], [ETIKETTNAME])
);

CREATE TABLE [FRAGEBOGEN] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [FRAGEBOGENART] varchar(1) ,
  [LFDFRAGEBOGEN] varchar(3) ,
  [DATUM] varchar(8) ,
  [BEZEICHNUNG] varchar(80) ,
  [FBELSE] varchar(80) ,
  CONSTRAINT [PK_FRAGEBOGEN] PRIMARY KEY ([MDID], [FRAGEBOGENART], [LFDFRAGEBOGEN])
);

CREATE TABLE [FRAGEBOGENENTRY] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [FRAGEBOGENART] varchar(1) ,
  [LFDFRAGEBOGEN] varchar(3) ,
  [LFDFRAGEBOGENENTRY] varchar(3) ,
  [LFDGROUP] varchar(3) ,
  [LFDZEILE] varchar(3) ,
  [CONTROL] varchar(1) ,
  [ENTRYSTATUS] varchar(1) ,
  [FRAGETEXT] varchar(160) ,
  [ANTWORTINTROTEXT] varchar(50) ,
  [ANTWORTART] varchar(1) ,
  [ANTWORTTHERAPIE] varchar(10) ,
  [ANTWORTSTATUS] varchar(1) ,
  [FBEELSE1] varchar(80) ,
  [FBEELSE2] varchar(80) ,
  [FBEELSE3] varchar(80) ,
  [PFLICHT] varchar(1) ,
  CONSTRAINT [PK_FRAGEBOGENENTRY] PRIMARY KEY ([MDID], [FRAGEBOGENART], [LFDFRAGEBOGEN], [LFDFRAGEBOGENENTRY])
);

CREATE TABLE [FREITEXT] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [FREITEXTART] varchar(1) ,
  [LFDNR1] varchar(3) ,
  [LFDNR2] varchar(3) ,
  [LFDZEILE] varchar(3) ,
  [LFDGRUPPE] varchar(3) ,
  [ZUSATZINFO] varchar(10) ,
  [ZUSATZINFO2] varchar(50) ,
  [BESCHREIBUNG] varchar(160) ,
  [TODO] varchar(1) ,
  CONSTRAINT [PK_FREITEXT] PRIMARY KEY ([PATNR], [FREITEXTART], [LFDNR1], [LFDNR2], [LFDZEILE])
);

CREATE TABLE [GEMATIKERROR] (
  [RINFO] varchar(34) ,
  [GEMATIKMANDANTID] varchar(2) ,
  [CONNECTORID] varchar(1) ,
  [RESULT] varchar(1) ,
  [MESSAGEID] varchar(36) ,
  [ZEITSTEMPEL] varchar(14) ,
  CONSTRAINT [PK_GEMATIKERROR] PRIMARY KEY ([RINFO])
);

CREATE TABLE [GEMATIKEVENT] (
  [RINFO] varchar(34) ,
  [GEMATIKMANDANTID] varchar(2) ,
  [CONNECTORID] varchar(1) ,
  [TOPIC] varchar(254) ,
  [TYP] varchar(1) ,
  [SEVERITY] varchar(1) ,
  [SUBSCRIPTIONID] varchar(64) ,
  [PARAMETER] varchar(max) ,
  CONSTRAINT [PK_GEMATIKEVENT] PRIMARY KEY ([RINFO])
);

CREATE TABLE [GEMATIKTRACE] (
  [RINFO] varchar(34) ,
  [LFDTRACE] varchar(2) ,
  [EVENTID] varchar(100) ,
  [INSTANCE] varchar(100) ,
  [LOGREFERENCE] varchar(100) ,
  [COMPTYPE] varchar(64) ,
  [CODE] varchar(5) ,
  [SEVERITY] varchar(1) ,
  [ERRORTYPE] varchar(1) ,
  [ERRORTEXT] varchar(250) ,
  [DETAIL] varchar(max) ,
  CONSTRAINT [PK_GEMATIKTRACE] PRIMARY KEY ([RINFO], [LFDTRACE])
);

CREATE TABLE [GERAETE] (
  [RINFO] varchar(34) ,
  [GERAETEID] varchar(5) ,
  [VALID] varchar(1) ,
  [NAME] varchar(30) ,
  [HERSTELLER] varchar(30) ,
  [TYP] varchar(30) ,
  [GRUPPE] varchar(8) ,
  [KATEGORIE] varchar(1) ,
  [SERIENNUMMER] varchar(30) ,
  [FABRIKNUMMER] varchar(30) ,
  [VERANTWORTLICHER] varchar(3) ,
  [STANDORT] varchar(30) ,
  [WORKSTATION] varchar(3) ,
  [ADRID] varchar(6) ,
  [GARANTIEDATUM] varchar(8) ,
  [LIEFERDATUM] varchar(8) ,
  [KONTROLLDATUM] varchar(8) ,
  [KTRWARNINTERVALL] varchar(2) ,
  [KTRWARNDATUM] varchar(8) ,
  [ADRIDD] varchar(6) ,
  [STOERUNGSZEIT] varchar(17) ,
  [STOERUNGSTEXT] varchar(254) ,
  [STOERUNGSPID] varchar(3) ,
  [STOERUNGSZEIT2] varchar(17) ,
  [STOERUNGSTEXT2] varchar(254) ,
  [STOERUNGSPID2] varchar(3) ,
  [STOERUNGSZEIT3] varchar(17) ,
  [STOERUNGSTEXT3] varchar(254) ,
  [STOERUNGSPID3] varchar(3) ,
  [QMKATEGORIE] varchar(1) ,
  [QMTITEL] varchar(254) ,
  [QMLINKZIEL] varchar(254) ,
  [UUID] varchar(40) ,
  [STOERUNGSPRIOS] varchar(3) ,
  [STERIDEFAULT] varchar(11) ,
  CONSTRAINT [PK_GERAETE] PRIMARY KEY ([GERAETEID])
);
CREATE INDEX [K2GERAETE] ON [GERAETE] ([NAME]);

CREATE TABLE [GIPS] (
  [RINFO] varchar(34) ,
  [GIPSNR] varchar(6) ,
  [PATNR] varchar(10) ,
  [DATUM] varchar(8) ,
  [ARCHIVIERT] varchar(8) ,
  [GEDRUCKT] varchar(1) ,
  [ART] varchar(1) ,
  [LEBID] varchar(3) ,
  [BESCHREIBUNG] varchar(80) ,
  CONSTRAINT [PK_GIPS] PRIMARY KEY ([GIPSNR], [ART], [PATNR], [ARCHIVIERT])
);
CREATE UNIQUE INDEX [K2GIPS] ON [GIPS] ([PATNR], [GIPSNR], [ART], [ARCHIVIERT]);
CREATE UNIQUE INDEX [K3GIPS] ON [GIPS] ([ARCHIVIERT], [GIPSNR], [ART], [PATNR]);

CREATE TABLE [GLBLOC] (
  [RINFO] varchar(34) ,
  [LFDGLKU] varchar(4) ,
  [LFDGLBLOC] varchar(6) ,
  [GLBLOCART] varchar(1) ,
  [FIKTIV] varchar(1) ,
  [PATNR] varchar(10) ,
  [PATVORNAME] varchar(28) ,
  [PATNAME] varchar(28) ,
  [TITEL] varchar(28) ,
  [NAMENSZUSATZ] varchar(15) ,
  [GEBDATUM] varchar(8) ,
  [ADRID] varchar(6) ,
  [MDID] varchar(2) ,
  [LEBID] varchar(3) ,
  [Z1PATNR] varchar(10) ,
  [LFDPLAN] varchar(3) ,
  [LFDLBLOCK] varchar(3) ,
  [ABRSTATUS] varchar(1) ,
  [LFDGLKUFAKT] varchar(6) ,
  [DATUM1] varchar(8) ,
  [DATUM2] varchar(8) ,
  [DATUM3] varchar(8) ,
  [DATUM4] varchar(8) ,
  [DATUM5] varchar(8) ,
  [ABRADRID] varchar(6) ,
  [TERMIN] varchar(80) ,
  [TBEMERKUNG] varchar(240) ,
  [NETTOSUM] varchar(100) ,
  [USTSUM] varchar(100) ,
  [USTKEY] varchar(100) ,
  [BRUTTOSUM] varchar(100) ,
  [GL1] varchar(100) ,
  [GL2] varchar(100) ,
  [GL3] varchar(100) ,
  [GL4] varchar(100) ,
  [GL5] varchar(100) ,
  [LFDGLABRECH] varchar(10) ,
  CONSTRAINT [PK_GLBLOC] PRIMARY KEY ([LFDGLKU], [LFDGLBLOC])
);

CREATE TABLE [GLBLOCENTRY] (
  [RINFO] varchar(34) ,
  [LFDGLKU] varchar(4) ,
  [LFDGLBLOC] varchar(6) ,
  [LFDGLBLOCENTRY] varchar(3) ,
  [GLBLOCENTRYART] varchar(1) ,
  [GOART] varchar(1) ,
  [LSTNR] varchar(6) ,
  [KYLSTNR] varchar(6) ,
  [ANZAHL] varchar(6) ,
  [ENDGEWICHT] varchar(6) ,
  [EINZELBETRAG] varchar(10) ,
  [USTKEY] varchar(1) ,
  [ABR] varchar(1) ,
  [ABRSTATUS] varchar(1) ,
  [DATUM] varchar(8) ,
  [LEBID] varchar(3) ,
  [BEMERKUNG1] varchar(100) ,
  [BEMERKUNG2] varchar(100) ,
  [CHARGE] varchar(30) ,
  CONSTRAINT [PK_GLBLOCENTRY] PRIMARY KEY ([LFDGLKU], [LFDGLBLOC], [LFDGLBLOCENTRY])
);

CREATE TABLE [GLKU] (
  [RINFO] varchar(34) ,
  [LFDGLKU] varchar(4) ,
  [GLKUART] varchar(1) ,
  [GLKUNAME] varchar(40) ,
  [ADRID1] varchar(6) ,
  [ADRID2] varchar(6) ,
  [RABATTPC] varchar(45) ,
  [SKONTOPC] varchar(45) ,
  [SKONTOBISTAGE] varchar(3) ,
  [GLKU1] varchar(100) ,
  [GLKU2] varchar(100) ,
  [GLKU3] varchar(100) ,
  [GLKU4] varchar(100) ,
  [GLKU5] varchar(100) ,
  CONSTRAINT [PK_GLKU] PRIMARY KEY ([LFDGLKU])
);

CREATE TABLE [GLKUFAKT] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [LFDGLKU] varchar(4) ,
  [LFDGLKUFAKT] varchar(6) ,
  [LFDFAKTREF] varchar(6) ,
  [FAKTDATUM] varchar(8) ,
  [ABRADRID] varchar(6) ,
  [VONDATUM] varchar(8) ,
  [BISDATUM] varchar(8) ,
  [ANZGBLOCKS] varchar(6) ,
  [RABATTPC] varchar(45) ,
  [SKONTOPC] varchar(45) ,
  [SKONTOBISTAGE] varchar(3) ,
  [RART] varchar(4) ,
  [EXPECTLFDBANK] varchar(2) ,
  [FORDKTO] varchar(6) ,
  [ERLOESKTO] varchar(6) ,
  [BESCHREIBUNG] varchar(30) ,
  [Z1INTERN] varchar(30) ,
  [BELEG] varchar(8) ,
  [FTRANSFERED] varchar(1) ,
  [NETTOSUM] varchar(100) ,
  [USTSUM] varchar(100) ,
  [USTKEY] varchar(100) ,
  [BRUTTOSUM] varchar(100) ,
  [BEGLICHEN] varchar(10) ,
  [AUSGEBUCHT] varchar(10) ,
  [STORNIERT] varchar(1) ,
  [MAHNSTUFE] varchar(1) ,
  [LASTMAHNDATUM] varchar(8) ,
  [AUFSCHUBDATUM] varchar(8) ,
  [MAHNERLAUBNIS] varchar(1) ,
  CONSTRAINT [PK_GLKUFAKT] PRIMARY KEY ([MDID], [LFDGLKU], [LFDGLKUFAKT])
);
CREATE UNIQUE INDEX [K2GLKUFAKT] ON [GLKUFAKT] ([MDID], [FAKTDATUM], [LFDGLKU], [LFDGLKUFAKT]);

CREATE TABLE [GO] (
  [RINFO] varchar(34) ,
  [LSTNR] varchar(6) ,
  [KYLSTNR] varchar(6) ,
  [LSTKUERZEL] varchar(6) ,
  [KYLSTKUERZEL] varchar(6) ,
  [DRUCKBILD] varchar(7) ,
  [ANALOGNR] varchar(6) ,
  [ANALOGGOART] varchar(1) ,
  [ABDATUM] varchar(8) ,
  [BISDATUM] varchar(8) ,
  [GOART] varchar(1) ,
  [GOSUBART] varchar(1) ,
  [GOSUBSUBART] varchar(3) ,
  [PWLART] varchar(1) ,
  [ABRART] varchar(1) ,
  [STATISTIKART] varchar(1) ,
  [KURZTEXT] varchar(60) ,
  [LANGTEXT1] varchar(60) ,
  [LANGTEXT2] varchar(60) ,
  [LANGTEXT3] varchar(60) ,
  [LANGTEXT4] varchar(60) ,
  [LANGTEXT5] varchar(60) ,
  [LANGTEXT6] varchar(60) ,
  [ABRECHENBAR] varchar(1) ,
  [ALLGKOSTEN] varchar(7) ,
  [ZUSCHLAG] varchar(7) ,
  [ZUZAHLUNGBMAE] varchar(9) ,
  [ZUZAHLUNGEGO] varchar(9) ,
  [DMBETRAG] varchar(9) ,
  [BEMAKUERZEL] varchar(6) ,
  [DTANR] varchar(6) ,
  [KFONR] varchar(6) ,
  [SONDERPUNKTWERT] varchar(9) ,
  [GEBPKT] varchar(8) ,
  [COMPUTE1FACH] varchar(1) ,
  [EINFACHSATZ] varchar(10) ,
  [EINFACHSATZB] varchar(10) ,
  [STDFAKTOR] varchar(6) ,
  [PRAXFAKTOR] varchar(6) ,
  [GOUSTKEY] varchar(5) ,
  [LAB1PREIS] varchar(10) ,
  [LAB2PREIS] varchar(10) ,
  [LAB3PREIS] varchar(10) ,
  [LAB4PREIS] varchar(10) ,
  [LAB5PREIS] varchar(10) ,
  [MINDESTBESTAND] varchar(9) ,
  [BESTELLMENGE] varchar(9) ,
  [BESTAND] varchar(9) ,
  [SCHLEIFRESTE] varchar(9) ,
  [BESTANDTEILE] varchar(220) ,
  [BEGRVORSCHLAG] varchar(240) ,
  [ASKBEGR] varchar(30) ,
  [DOKUVORSCHLAG] varchar(240) ,
  [ASKDOKU] varchar(30) ,
  [GOARTVORSCHLAG] varchar(10) ,
  [LSTVORSCHLAG] varchar(60) ,
  [ASKVORSCHLAG] varchar(10) ,
  [ZAHNANGABE] varchar(1) ,
  [NEUERBEFUND] varchar(1) ,
  [BUDGET] varchar(102) ,
  [LCHECK] varchar(40) ,
  [GOSONST1] varchar(254) ,
  CONSTRAINT [PK_GO] PRIMARY KEY ([GOART], [KYLSTNR], [ABDATUM])
);
CREATE UNIQUE INDEX [K2GO] ON [GO] ([GOART], [KYLSTKUERZEL], [ABDATUM]);
CREATE UNIQUE INDEX [K3GO] ON [GO] ([GOART], [GOSUBART], [KYLSTNR], [ABDATUM]);
CREATE UNIQUE INDEX [K4GO] ON [GO] ([GOART], [GOSUBART], [KYLSTKUERZEL], [ABDATUM]);

CREATE TABLE [GOBUDGET] (
  [RINFO] varchar(34) ,
  [GOART] varchar(1) ,
  [LSTKUERZEL] varchar(6) ,
  [KYLSTKUERZEL] varchar(6) ,
  [ABDATUM] varchar(8) ,
  [F100RVO] varchar(5) ,
  [F100VDEK] varchar(5) ,
  [F100GESAMT] varchar(5) ,
  [AF100RVO] varchar(5) ,
  [AF100VDEK] varchar(5) ,
  [AF100GESAMT] varchar(5) ,
  [LFDNR] varchar(4) ,
  CONSTRAINT [PK_GOBUDGET] PRIMARY KEY ([GOART], [KYLSTKUERZEL], [ABDATUM])
);
CREATE INDEX [K2GOBUDGET] ON [GOBUDGET] ([GOART], [ABDATUM], [LFDNR]);

CREATE TABLE [GOCHECK] (
  [RINFO] varchar(34) ,
  [GOART] varchar(1) ,
  [LSTNR] varchar(6) ,
  [KYLSTNR] varchar(6) ,
  [LFDCHECK] varchar(3) ,
  [CHECKAB] varchar(8) ,
  [CHECKBIS] varchar(8) ,
  [SCHWEREGRAD] varchar(1) ,
  [AGOART] varchar(1) ,
  [AGOSUBART] varchar(1) ,
  [AGOSUBSUBART] varchar(3) ,
  [ALSTNR] varchar(6) ,
  [BGOART] varchar(1) ,
  [BGOSUBART] varchar(1) ,
  [BGOSUBSUBART] varchar(3) ,
  [BLSTNR] varchar(6) ,
  [MAXANZ] varchar(3) ,
  [ZEITRAUM] varchar(3) ,
  [ZEITRAUMCOEX] varchar(1) ,
  [WOCHENTAG] varchar(7) ,
  [MUSSBEGR] varchar(1) ,
  [MUSSADU] varchar(1) ,
  [MUSSORGAN] varchar(1) ,
  [MUSSMEDIKAMENT] varchar(1) ,
  [MUSSDATUM] varchar(1) ,
  [MUSSUHRZEIT] varchar(1) ,
  [AUHRZEIT] varchar(4) ,
  [BUHRZEIT] varchar(4) ,
  [BUHRZEITEXCL] varchar(1) ,
  [SEX] varchar(1) ,
  [AALTER] varchar(4) ,
  [BALTER] varchar(4) ,
  [BALTEREXCL] varchar(1) ,
  [ERLAUBTALTER] varchar(1) ,
  [BEREICH] varchar(1) ,
  [BEREICHCOEX] varchar(1) ,
  [BEFUND] varchar(30) ,
  [EXTRA] varchar(254) ,
  CONSTRAINT [PK_GOCHECK] PRIMARY KEY ([GOART], [KYLSTNR], [LFDCHECK])
);

CREATE TABLE [GOSUBSUB] (
  [RINFO] varchar(34) ,
  [GOART] varchar(1) ,
  [GOSUBART] varchar(1) ,
  [GOSUBSUBART] varchar(3) ,
  [SPARTE] varchar(2) ,
  [SUBSPARTE] varchar(10) ,
  [SUBSUBSPARTE] varchar(10) ,
  [BESCHREIBUNG] varchar(80) ,
  CONSTRAINT [PK_GOSUBSUB] PRIMARY KEY ([GOART], [GOSUBART], [GOSUBSUBART])
);
CREATE INDEX [K2GOSUBSUB] ON [GOSUBSUB] ([GOART], [GOSUBART], [SPARTE]);

CREATE TABLE [GOTEXTENTRY] (
  [RINFO] varchar(34) ,
  [GOART] varchar(1) ,
  [LSTNR] varchar(6) ,
  [KYLSTNR] varchar(6) ,
  [LFDENTRY] varchar(3) ,
  [ENTRYTYP] varchar(1) ,
  [ENTRY] varchar(254) ,
  CONSTRAINT [PK_GOTEXTENTRY] PRIMARY KEY ([GOART], [KYLSTNR], [LFDENTRY])
);

CREATE TABLE [GTEXT] (
  [RINFO] varchar(34) ,
  [SEITE] varchar(1) ,
  [GLIEDERUNG] varchar(3) ,
  [GLIEDERUNGSTEXT] varchar(80) ,
  CONSTRAINT [PK_GTEXT] PRIMARY KEY ([SEITE], [GLIEDERUNG])
);

CREATE TABLE [HISTAUFGABEN] (
  [RINFO] varchar(34) ,
  [ART] varchar(1) ,
  [PID] varchar(3) ,
  [TEAMLFDNR] varchar(5) ,
  [WORKSTATION] varchar(3) ,
  [AUFGABENID] varchar(10) ,
  [GERAETEID] varchar(5) ,
  [BESCHREIBUNG] varchar(254) ,
  [ADRIDT] varchar(6) ,
  [REPKOSTEN] varchar(9) ,
  [STOERUNGSPRIO] varchar(1) ,
  CONSTRAINT [PK_HISTAUFGABEN] PRIMARY KEY ([RINFO])
);
CREATE UNIQUE INDEX [K2HISTAUFGABEN] ON [HISTAUFGABEN] ([ART], [RINFO]);
CREATE INDEX [K3HISTAUFGABEN] ON [HISTAUFGABEN] ([ART], [AUFGABENID], [TEAMLFDNR], [PID]);
CREATE INDEX [K4HISTAUFGABEN] ON [HISTAUFGABEN] ([ART], [GERAETEID]);

CREATE TABLE [HISTPERSONAL] (
  [RINFO] varchar(34) ,
  [PID] varchar(3) ,
  [ABDATUM] varchar(8) ,
  [BISDATUM] varchar(8) ,
  [KUERZEL] varchar(6) ,
  [ADRID] varchar(6) ,
  [JOINED] varchar(1) ,
  CONSTRAINT [PK_HISTPERSONAL] PRIMARY KEY ([PID], [BISDATUM])
);

CREATE TABLE [HISTRECALL] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [RECALLDATUM] varchar(8) ,
  [RECALLART] varchar(2) ,
  [BENACHRICHTIGUNG] varchar(1) ,
  [WIEDERHOLUNG] varchar(1) ,
  CONSTRAINT [PK_HISTRECALL] PRIMARY KEY ([PATNR], [RECALLDATUM], [RECALLART])
);

CREATE TABLE [HISTUEBERW] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LFDHISTORIE] varchar(4) ,
  [MDID] varchar(2) ,
  [DATUM] varchar(8) ,
  [LEBID] varchar(3) ,
  [UEBERWEISUNGSART] varchar(1) ,
  [UGLISTSELECTEDINDEX] varchar(1) ,
  [UEBERWEISUNGSGRUND] varchar(60) ,
  [UG1] varchar(2) ,
  [UB] varchar(29) ,
  [VL] varchar(47) ,
  [UG2] varchar(3) ,
  [VLUB] varchar(max) ,
  [KB] varchar(33) ,
  [BSDATUM] varchar(8) ,
  [BZEILE1] varchar(47) ,
  [BZEILE2] varchar(47) ,
  [BZEILE3] varchar(47) ,
  [BZEILE4] varchar(25) ,
  [BZEILE5] varchar(25) ,
  [GF] varchar(1) ,
  [UODERV] varchar(2) ,
  [VERKEHR] varchar(3) ,
  [SODERL] varchar(2) ,
  [EDESVDATUM] varchar(8) ,
  [AODERUSCHEIN1] varchar(3) ,
  [AODERUSCHEIN2] varchar(3) ,
  [UART1] varchar(4) ,
  [EDITFIELDQNR] varchar(1) ,
  [EDITFIELDJAHR] varchar(2) ,
  [UUNDU] varchar(1) ,
  [DATUMDEROP] varchar(8) ,
  [GESCHLECHT] varchar(1) ,
  [UAN] varchar(47) ,
  [UART2] varchar(3) ,
  [AUBISDATUM] varchar(8) ,
  [EL] varchar(1) ,
  [DODERVZEILE1] varchar(65) ,
  [DODERVZEILE2] varchar(65) ,
  [BODERMZEILE1] varchar(65) ,
  [BODERMZEILE2] varchar(65) ,
  [AUFTRAGZEILE1] varchar(65) ,
  [AUFTRAGZEILE2] varchar(65) ,
  [AUFTRAGZEILE3] varchar(65) ,
  [AUFTRAGZEILE4] varchar(65) ,
  CONSTRAINT [PK_HISTUEBERW] PRIMARY KEY ([PATNR], [LFDHISTORIE])
);
CREATE UNIQUE INDEX [K2HISTUEBERW] ON [HISTUEBERW] ([UEBERWEISUNGSART], [PATNR], [LFDHISTORIE]);

CREATE TABLE [HMPREIS] (
  [RINFO] varchar(34) ,
  [HMPID] varchar(5) ,
  [KYHMPID] varchar(5) ,
  [LFDNR] varchar(3) ,
  [BEREICH] varchar(1) ,
  [BEZEICHNUNG] varchar(254) ,
  [BEMERKUNGEN] varchar(254) ,
  [GUELTIGAB] varchar(8) ,
  [PREISVORGABE] varchar(7) ,
  [PRAXISPREIS] varchar(7) ,
  CONSTRAINT [PK_HMPREIS] PRIMARY KEY ([KYHMPID], [LFDNR])
);

CREATE TABLE [ICD] (
  [RINFO] varchar(34) ,
  [ICDCODE] varchar(5) ,
  [KYICDCODE] varchar(5) ,
  [KAPITEL] varchar(8) ,
  [KYKAPITEL] varchar(8) ,
  [GRUPPE] varchar(8) ,
  [KYGRUPPE] varchar(8) ,
  [SUBGROUP] varchar(8) ,
  [KYSUBGROUP] varchar(8) ,
  [ICDNOTATIONSKZ] varchar(1) ,
  [BASISSCHLUESSELKZ] varchar(1) ,
  [SEX] varchar(2) ,
  [VONALTER] varchar(5) ,
  [BISALTER] varchar(5) ,
  [EXOTISCH] varchar(1) ,
  [SCHLUESSELBELEGT] varchar(1) ,
  [MELDEPFLICHTIG] varchar(1) ,
  [ABRECHBESONDERHEIT] varchar(1) ,
  [BESCHREIBUNG] varchar(254) ,
  [AKRREF] varchar(160) ,
  [SEKUNDAERCODE] varchar(5) ,
  [KYSEKUNDAERCODE] varchar(5) ,
  [ZAHNMEDIZINAU] varchar(1) ,
  [ARZTGRUPPE] varchar(160) ,
  CONSTRAINT [PK_ICD] PRIMARY KEY ([KYICDCODE])
);
CREATE UNIQUE INDEX [K2ICD] ON [ICD] ([BASISSCHLUESSELKZ], [KYKAPITEL], [KYGRUPPE], [KYSUBGROUP], [KYICDCODE]);

CREATE TABLE [INFODOKU] (
  [RINFO] varchar(34) ,
  [AUTORID] varchar(2) ,
  [DOKUID] varchar(4) ,
  [KATEGORIE] varchar(1) ,
  [LINKTEXT] varchar(60) ,
  [LINKZIEL] varchar(100) ,
  [PRIO] varchar(1) ,
  [EXTRAS] varchar(1) ,
  [MINANZCALLS] varchar(2) ,
  CONSTRAINT [PK_INFODOKU] PRIMARY KEY ([AUTORID], [DOKUID])
);

CREATE TABLE [INFODOKUENTRY] (
  [RINFO] varchar(34) ,
  [AUTORID] varchar(2) ,
  [DOKUID] varchar(4) ,
  [PID] varchar(3) ,
  [ANZCALLS] varchar(2) ,
  [INFOSTATUS] varchar(1) ,
  CONSTRAINT [PK_INFODOKUENTRY] PRIMARY KEY ([AUTORID], [DOKUID], [PID])
);

CREATE TABLE [INFODOKUTRIGGER] (
  [RINFO] varchar(34) ,
  [AUTORID] varchar(2) ,
  [DOKUID] varchar(4) ,
  [LFDTRIGGER] varchar(2) ,
  [VONDATUM] varchar(8) ,
  [BISDATUM] varchar(8) ,
  [WOCHENTAGE] varchar(1) ,
  [INTERVALL] varchar(2) ,
  [INTERVALLART] varchar(1) ,
  [INTERVALLDAUER] varchar(2) ,
  [VONPLZ] varchar(20) ,
  [BISPLZ] varchar(20) ,
  [VSPID] varchar(2) ,
  [KZVNR] varchar(2) ,
  [KVNR] varchar(2) ,
  [PROGIDS] varchar(27) ,
  [OHNEPROGS] varchar(9) ,
  [FACHGEBIET] varchar(1) ,
  [TRIGGERDATEI] varchar(1) ,
  CONSTRAINT [PK_INFODOKUTRIGGER] PRIMARY KEY ([AUTORID], [DOKUID], [LFDTRIGGER])
);

CREATE TABLE [KBRHIT] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [PATNR] varchar(10) ,
  [LFDPATBILL] varchar(5) ,
  [ABRART] varchar(1) ,
  [GLFDPATVD] varchar(3) ,
  [GLFDFAKT] varchar(5) ,
  [LFDPLAN] varchar(3) ,
  [PRUEFCODE] varchar(160) ,
  [ABRSTATUS] varchar(1) ,
  [DTADATUM] varchar(8) ,
  [VERSICHERTENNR] varchar(12) ,
  [PATTITEL] varchar(28) ,
  [PATVORNAME] varchar(28) ,
  [KYPATVORNAME] varchar(28) ,
  [PATAPPENDIX] varchar(15) ,
  [PATNAME] varchar(28) ,
  [KYPATNAME] varchar(28) ,
  [PATPLZ] varchar(7) ,
  [PATORT] varchar(23) ,
  [PATGEBDATUM] varchar(8) ,
  [PATWLC] varchar(3) ,
  [PATSEX] varchar(1) ,
  [PATVORSATZ] varchar(20) ,
  [Z1KASKUERZEL] varchar(10) ,
  [VNACHWEIS] varchar(1) ,
  [EINLESEDATUM] varchar(8) ,
  [BKVKASNAME] varchar(30) ,
  [BKVKASNR] varchar(12) ,
  [ZUSTKZV] varchar(5) ,
  [MFRDIG] varchar(1) ,
  [RSADIG] varchar(3) ,
  [RSAART] varchar(1) ,
  [WSO] varchar(1) ,
  [GUELTIGABDATUM] varchar(8) ,
  [GUELTIGBISDATUM] varchar(8) ,
  [DTABEMERKUNG] varchar(254) ,
  [AZSOKTR] varchar(50) ,
  [PM] varchar(1) ,
  [KZVINTERN] varchar(254) ,
  [KZVINTERN2] varchar(254) ,
  [DATLASTAE1] varchar(8) ,
  [DATLAST01] varchar(8) ,
  [DATLASTFU] varchar(8) ,
  [VORHZAEHNE] varchar(160) ,
  [PLANUNGSDATUM] varchar(8) ,
  [SUMELAB] varchar(7) ,
  [SUMFLAB] varchar(7) ,
  [SUMTOTAL] varchar(10) ,
  [FALLBESONDERHEIT] varchar(10) ,
  [VERSART] varchar(1) ,
  [ANTRAGSNUMMER] varchar(80) ,
  CONSTRAINT [PK_KBRHIT] PRIMARY KEY ([MDID], [PATNR], [LFDPLAN])
);
CREATE UNIQUE INDEX [K2KBRHIT] ON [KBRHIT] ([MDID], [DTADATUM], [KYPATNAME], [KYPATVORNAME], [PATGEBDATUM], [PATNR], [LFDPLAN]);

CREATE TABLE [KBRHITLST] (
  [RINFO] varchar(34) ,
  [MODUS] varchar(1) ,
  [MDID] varchar(2) ,
  [PATNR] varchar(10) ,
  [LFDPLAN] varchar(3) ,
  [LFDLST] varchar(3) ,
  [PRUEFCODE] varchar(4) ,
  [LSTDATUM] varchar(8) ,
  [SITZKENNZ] varchar(1) ,
  [ZAHN] varchar(5) ,
  [LSTNR] varchar(5) ,
  [ANZBEM] varchar(6) ,
  [DATLASTLST] varchar(8) ,
  [KZVINTERN] varchar(254) ,
  [FLAGNOHINWEIS] varchar(1) ,
  [RECHNMWSTID] varchar(2) ,
  [BEZEICHNUNG] varchar(4) ,
  [MATERIALBEZ] varchar(60) ,
  [BETRAG] varchar(7) ,
  [ANZMWST] varchar(3) ,
  CONSTRAINT [PK_KBRHITLST] PRIMARY KEY ([MDID], [PATNR], [LFDPLAN], [LFDLST], [MODUS])
);

CREATE TABLE [KFOBEFUND] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LFDKFOBEFUND] varchar(3) ,
  [UNTERZAHL] varchar(12) ,
  [UEBERZAHL] varchar(12) ,
  [LATEZAHNWECHSEL] varchar(1) ,
  [DIFFICULTBEH] varchar(1) ,
  [LATEREAKTION] varchar(1) ,
  [BADMITARBEIT] varchar(1) ,
  [BEHANDLUNGSDAUER] varchar(2) ,
  [GEPLANTEQUARTS] varchar(2) ,
  [ABRQUARTSVORZ1] varchar(2) ,
  [ABGERECHNETEQUARTS] varchar(2) ,
  [BEHSTARTDATUM] varchar(8) ,
  [BEHENDDATUM] varchar(8) ,
  [ERSTANTRAGDATUM] varchar(8) ,
  [ERSTANTRAGSTARTDATUM] varchar(8) ,
  [RESTARTDATUMGEPLANT] varchar(8) ,
  [BISSLAGEI] varchar(6) ,
  [BISSLAGEII] varchar(6) ,
  [BISSLAGEIII] varchar(6) ,
  [BISSLAGEIV] varchar(6) ,
  [BISSLAGEP] varchar(10) ,
  [UMFORMOKI] varchar(6) ,
  [UMFORMOKII] varchar(6) ,
  [UMFORMOKIII] varchar(6) ,
  [UMFORMOKIV] varchar(6) ,
  [UMFORMOKV] varchar(6) ,
  [UMFORMOKP] varchar(10) ,
  [UMFORMUKI] varchar(6) ,
  [UMFORMUKII] varchar(6) ,
  [UMFORMUKIII] varchar(6) ,
  [UMFORMUKIV] varchar(6) ,
  [UMFORMUKV] varchar(6) ,
  [UMFORMUKP] varchar(10) ,
  [KIG] varchar(2) ,
  CONSTRAINT [PK_KFOBEFUND] PRIMARY KEY ([PATNR], [LFDKFOBEFUND])
);

CREATE TABLE [KFOHIT] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [LFDFALL] varchar(5) ,
  [PATNR] varchar(10) ,
  [LFDPATBILL] varchar(5) ,
  [ABRART] varchar(1) ,
  [ABRPERDTA] varchar(1) ,
  [GLFDPATVD] varchar(3) ,
  [GKTRAEGER] varchar(1) ,
  [PLFDPATVD] varchar(3) ,
  [PKTRAEGER] varchar(1) ,
  [PLFDFAKT] varchar(5) ,
  [VONDATUM] varchar(8) ,
  [BISDATUM] varchar(8) ,
  [LFDPLAN] varchar(3) ,
  [LFDKFOSTATUS] varchar(3) ,
  [SUCHLAUFQYY] varchar(3) ,
  [LFDPATFALL] varchar(1) ,
  [KFOPOS] varchar(8) ,
  [KFOLEN] varchar(6) ,
  [DTASORTKEY] varchar(24) ,
  [PATTITEL] varchar(28) ,
  [PATVORNAME] varchar(28) ,
  [PATAPPENDIX] varchar(15) ,
  [PATNAME] varchar(28) ,
  [PATSTRASSE] varchar(30) ,
  [PATPLZ] varchar(7) ,
  [PATORT] varchar(23) ,
  [PATGEBDATUM] varchar(8) ,
  [Z1KASKUERZEL] varchar(10) ,
  [VNACHWEIS] varchar(1) ,
  [BEHINDERT] varchar(1) ,
  [EINLESEDATUM] varchar(8) ,
  [KVKKASNAME] varchar(28) ,
  [KVKKASNR] varchar(9) ,
  [VERSICHERTENNR] varchar(12) ,
  [MFRDIG] varchar(1) ,
  [RSA] varchar(3) ,
  [WSO] varchar(1) ,
  [GUELTIGBISDATUM] varchar(8) ,
  [AKTENZEICHEN] varchar(60) ,
  [CHECKSTATUS] varchar(80) ,
  [LSTUNBEKANNT] varchar(60) ,
  [DRUCKSTATUS] varchar(1) ,
  [PWKC] varchar(9) ,
  [PWIP] varchar(9) ,
  [PWKFO] varchar(9) ,
  [PKTSUMKC] varchar(6) ,
  [PKTSUMIP] varchar(6) ,
  [PKTSUMKFO] varchar(6) ,
  [ZAHONORAR] varchar(10) ,
  [SUMELAB] varchar(10) ,
  [SUMPMAT] varchar(10) ,
  [SUMFLAB] varchar(10) ,
  [SUMTOTAL] varchar(10) ,
  [KFO1] varchar(80) ,
  [KFO2] varchar(80) ,
  [KFO3] varchar(80) ,
  [KFO4] varchar(80) ,
  [KZVINTERN] varchar(50) ,
  [KFO5] varchar(254) ,
  CONSTRAINT [PK_KFOHIT] PRIMARY KEY ([MDID], [LFDFALL])
);
CREATE UNIQUE INDEX [K2KFOHIT] ON [KFOHIT] ([MDID], [DTASORTKEY]);

CREATE TABLE [KOMLEMAIL] (
  [RINFO] varchar(34) ,
  [LFDNR] varchar(8) ,
  [POSTFACH] varchar(1) ,
  [PATNR] varchar(10) ,
  [ZEITSTEMPEL] varchar(14) ,
  [MAILFROM] varchar(254) ,
  [MAILTO] varchar(254) ,
  [SUBJECT] varchar(254) ,
  [GEMATIKMANDANTID] varchar(2) ,
  [PID] varchar(3) ,
  [ZEITSTEMPEL2] varchar(14) ,
  [MESSAGEID] varchar(254) ,
  [KOMLEFLAGS] varchar(20) ,
  [DIENSTKENNUNG] varchar(3) ,
  [NAMEFROM] varchar(80) ,
  [NAMETO] varchar(80) ,
  CONSTRAINT [PK_KOMLEMAIL] PRIMARY KEY ([LFDNR])
);
CREATE UNIQUE INDEX [K2KOMLEMAIL] ON [KOMLEMAIL] ([POSTFACH], [PATNR], [LFDNR]);
CREATE INDEX [K3KOMLEMAIL] ON [KOMLEMAIL] ([MESSAGEID]);

CREATE TABLE [KONTO] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [JAHR] varchar(4) ,
  [KTO] varchar(6) ,
  [KTOKUERZEL] varchar(6) ,
  [KYKTOKUERZEL] varchar(6) ,
  [KTOBESCHREIBUNG] varchar(40) ,
  [KABUFREIGABE] varchar(1) ,
  [ADRID] varchar(6) ,
  [USTKEY] varchar(1) ,
  [ABSCHLUSSART] varchar(1) ,
  [ABSCHLUSSKTO] varchar(6) ,
  [SEITE1] varchar(1) ,
  [GLIEDERUNG1] varchar(3) ,
  [SEITE2] varchar(1) ,
  [GLIEDERUNG2] varchar(3) ,
  [ANLAGENKONTO] varchar(1) ,
  [SALDOUEBERNAHME] varchar(1) ,
  [INSTALLDATUM] varchar(8) ,
  [EBSOLL] varchar(13) ,
  [EBHABEN] varchar(13) ,
  [GESAMTS] varchar(13) ,
  [GESAMTH] varchar(13) ,
  [TSESTART] varchar(8) ,
  CONSTRAINT [PK_KONTO] PRIMARY KEY ([MDID], [JAHR], [KTO])
);
CREATE INDEX [K2KONTO] ON [KONTO] ([MDID], [JAHR], [KYKTOKUERZEL]);

CREATE TABLE [KTRAEGER] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [KTRAEGER] varchar(1) ,
  [RZABRWEG] varchar(1) ,
  [RZABRNR] varchar(10) ,
  [RZVERSION] varchar(1) ,
  [ADRID] varchar(6) ,
  [BESCHREIBUNG] varchar(40) ,
  [PASSWORT] varchar(20) ,
  [RZEMAILUEBERT] varchar(1) ,
  CONSTRAINT [PK_KTRAEGER] PRIMARY KEY ([MDID], [KTRAEGER])
);

CREATE TABLE [KZV] (
  [RINFO] varchar(34) ,
  [KZVNR] varchar(2) ,
  [ABDATUM] varchar(8) ,
  [KZVNAME] varchar(30) ,
  [LQPUNKTWERT] varchar(6) ,
  [HKPFAKTOR] varchar(6) ,
  [STDZUSCHFAKTORZE] varchar(3) ,
  [STDZUSCHPROKRONE] varchar(7) ,
  [ZUSCHABFRMPAUSCH] varchar(1) ,
  [ZUSCHHUELSENPROVI] varchar(1) ,
  [ZUSCHDIRUF] varchar(1) ,
  [ZUSCHVERSAND] varchar(1) ,
  [VZENDEMONEY] varchar(1) ,
  [STDZUSCHFAKTORKFO] varchar(3) ,
  [BKVZWANG] varchar(1) ,
  [BKVFNAME] varchar(64) ,
  [BKVREADDATUM] varchar(8) ,
  [BMPRUEFZWANG] varchar(1) ,
  [DTANR] varchar(1) ,
  [CARDFLG] varchar(1) ,
  [FIKTIVFLG] varchar(1) ,
  [FIKTIVFLGFUERINLAYS] varchar(1) ,
  [BEGR4BEIPA] varchar(1) ,
  [BEGR5BEIZEINJEKTION] varchar(1) ,
  [BEGR5BEIZEBMF] varchar(1) ,
  [QAFORMULAR] varchar(1) ,
  [QDRUCKALPHABETISCH] varchar(1) ,
  [AOKSREGIONALZUSAMMEN] varchar(1) ,
  [LFDDRUCKPERMISSION] varchar(1) ,
  [LFDFORTLAUFEND] varchar(1) ,
  [LFDAUCHWENNKVKFEHLT] varchar(1) ,
  [KVKREADDATUMDRUCK] varchar(1) ,
  [QAKONTROLLZAHLDRUCK] varchar(1) ,
  [STAMMLEERBHD] varchar(1) ,
  [DRUCKADRAUFKLEBER] varchar(1) ,
  [DRUCKBEGLEITZETTEL] varchar(1) ,
  [GOPPERMISSION] varchar(1) ,
  [GNRZUSATZHANDLING] varchar(1) ,
  CONSTRAINT [PK_KZV] PRIMARY KEY ([KZVNR], [ABDATUM])
);

CREATE TABLE [LABAUFTRAG] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LFDPLAN] varchar(3) ,
  [LFDLBLOCK] varchar(3) ,
  [MANUELL] varchar(1) ,
  [GOLD1] varchar(20) ,
  [GOLD2] varchar(20) ,
  [GOLD3] varchar(20) ,
  [ARTIKULATOR] varchar(10) ,
  [ZAHNFORM1] varchar(80) ,
  [ZAHNFORM2] varchar(80) ,
  [ZAHNFARBEKUNSTSTOFF] varchar(20) ,
  [ZAHNFARBEGLAS] varchar(20) ,
  [ZAHNFARBEKERAMIK] varchar(20) ,
  [ZAHNFARBEZAHNERSATZ] varchar(20) ,
  [TERMIN1ART] varchar(1) ,
  [TERMIN1DATUM] varchar(8) ,
  [TERMIN1UHRZEIT] varchar(4) ,
  [TERMIN2ART] varchar(1) ,
  [TERMIN2DATUM] varchar(8) ,
  [TERMIN2UHRZEIT] varchar(4) ,
  [TERMIN3ART] varchar(1) ,
  [TERMIN3DATUM] varchar(8) ,
  [TERMIN3UHRZEIT] varchar(4) ,
  [TERMIN4ART] varchar(1) ,
  [TERMIN4DATUM] varchar(8) ,
  [TERMIN4UHRZEIT] varchar(4) ,
  [TERMIN5ART] varchar(1) ,
  [TERMIN5DATUM] varchar(8) ,
  [TERMIN5UHRZEIT] varchar(4) ,
  [TERMIN6ART] varchar(1) ,
  [TERMIN6DATUM] varchar(8) ,
  [TERMIN6UHRZEIT] varchar(4) ,
  [TERMIN7ART] varchar(1) ,
  [TERMIN7DATUM] varchar(8) ,
  [TERMIN7UHRZEIT] varchar(4) ,
  [DRUCKDATUM] varchar(8) ,
  [VERSANDDATUM] varchar(8) ,
  [AUFTRAGSID] varchar(36) ,
  [AUFTRAGSSTATUS] varchar(1) ,
  CONSTRAINT [PK_LABAUFTRAG] PRIMARY KEY ([PATNR], [LFDPLAN], [LFDLBLOCK])
);
CREATE INDEX [K2LABAUFTRAG] ON [LABAUFTRAG] ([AUFTRAGSID]);

CREATE TABLE [LAND] (
  [RINFO] varchar(34) ,
  [LANDKUERZEL] varchar(3) ,
  [KYLANDKUERZEL] varchar(3) ,
  [SYSTEM] varchar(1) ,
  [LANDNAME] varchar(30) ,
  [KYLANDNAME] varchar(30) ,
  [VORWAHL] varchar(20) ,
  [KYVORWAHL] varchar(20) ,
  [EUTO] varchar(12) ,
  [LANDWAEHRUNG] varchar(3) ,
  CONSTRAINT [PK_LAND] PRIMARY KEY ([KYLANDKUERZEL])
);
CREATE UNIQUE INDEX [K2LAND] ON [LAND] ([KYLANDNAME]);
CREATE INDEX [K3LAND] ON [LAND] ([KYVORWAHL]);

CREATE TABLE [LBLOCK] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LFDPLAN] varchar(3) ,
  [LFDLBLOCK] varchar(3) ,
  [LFDLBLOCKREF] varchar(3) ,
  [LBLOCKART] varchar(1) ,
  [LABOR] varchar(1) ,
  [LEERQUARTAL] varchar(1) ,
  [FIKTIV] varchar(1) ,
  [LEBID] varchar(3) ,
  [DATUM] varchar(8) ,
  [ANLAGEDATUM] varchar(8) ,
  [STORNODATUM] varchar(8) ,
  [REKLAMATIONSDATUM] varchar(8) ,
  [STATISTIKDATUM] varchar(8) ,
  [GLABSTATUS] varchar(1) ,
  [BETRAEGE] varchar(110) ,
  [MDID] varchar(2) ,
  [LFDLABRECH] varchar(10) ,
  [LFDFLAB] varchar(2) ,
  CONSTRAINT [PK_LBLOCK] PRIMARY KEY ([PATNR], [LFDPLAN], [LFDLBLOCK])
);
CREATE UNIQUE INDEX [K2LBLOCK] ON [LBLOCK] ([PATNR], [LFDPLAN], [LABOR], [LFDLBLOCK]);

CREATE TABLE [LBLOCKENTRY] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LFDPLAN] varchar(3) ,
  [LFDLBLOCK] varchar(3) ,
  [ART] varchar(1) ,
  [LABOR] varchar(1) ,
  [LFDLBLOCKENTRY] varchar(3) ,
  [GOART] varchar(1) ,
  [LSTNR] varchar(6) ,
  [KYLSTNR] varchar(6) ,
  [FLGLAGEN] varchar(6) ,
  [ANZAHL] varchar(6) ,
  [ENDGEWICHT] varchar(6) ,
  [EINZELBETRAG] varchar(11) ,
  [FAKTOR] varchar(6) ,
  [BEGRTB] varchar(8) ,
  [BEGRTBS] varchar(80) ,
  [USTKEY] varchar(1) ,
  [LBEABRMERKMAL] varchar(1) ,
  [ZAEHNE] varchar(18) ,
  [ABR] varchar(1) ,
  [DATUM] varchar(8) ,
  [LEBID] varchar(3) ,
  [BEMERKUNG] varchar(60) ,
  [CHARGE] varchar(30) ,
  [LFDPABEFUND] varchar(3) ,
  [ABRDATUM] varchar(8) ,
  CONSTRAINT [PK_LBLOCKENTRY] PRIMARY KEY ([PATNR], [LFDPLAN], [LFDLBLOCK], [LFDLBLOCKENTRY])
);
CREATE UNIQUE INDEX [K2LBLOCKENTRY] ON [LBLOCKENTRY] ([PATNR], [LFDPLAN], [LABOR], [LFDLBLOCK], [LFDLBLOCKENTRY]);

CREATE TABLE [LEB] (
  [RINFO] varchar(34) ,
  [LEBID] varchar(3) ,
  [ABDATUM] varchar(8) ,
  [VALID] varchar(1) ,
  [PID] varchar(3) ,
  [PRAXISID] varchar(3) ,
  [BSULANR] varchar(18) ,
  [MDIDK] varchar(2) ,
  [MDIDP] varchar(2) ,
  [TPSTATUS] varchar(1) ,
  [PROVIPROZ] varchar(50) ,
  [KVDTABHDKZ] varchar(3) ,
  [KVDTASONDERFELD] varchar(60) ,
  [EBM2KABRECHENBAR1] varchar(254) ,
  [EBM2KABRECHENBAR2] varchar(254) ,
  [EBM2KABRECHENBAR3] varchar(254) ,
  [EBM2KABRECHENBAR4] varchar(254) ,
  [EBM2KABRECHENBAR5] varchar(254) ,
  [EBM2KABRECHENBAR6] varchar(254) ,
  [EBM2KABRECHENBAR7] varchar(max) ,
  [STATPROZ] varchar(5) ,
  [UVSTATPROZ] varchar(5) ,
  [FARBE] varchar(6) ,
  [EXTERNID] varchar(36) ,
  [ZANR] varchar(26) ,
  [CINFO] varchar(34) ,
  [ASVTEAMNR] varchar(9) ,
  [ASVFACHGRUPPENNR] varchar(9) ,
  [BEZEICHNUNG] varchar(20) ,
  CONSTRAINT [PK_LEB] PRIMARY KEY ([LEBID], [ABDATUM])
);

CREATE TABLE [MAC] (
  [RINFO] varchar(34) ,
  [MACID] varchar(6) ,
  [KYMACID] varchar(6) ,
  [MACGO] varchar(1) ,
  [MACART] varchar(1) ,
  [MACROTEXT] varchar(60) ,
  [INNERBILD] varchar(3) ,
  [OUTERBILD] varchar(3) ,
  [BRUECKENVERWENDUNG] varchar(1) ,
  [VERBLENDART] varchar(1) ,
  [EXTENTIONSIMPLANTAT] varchar(1) ,
  [NEUERBEFUND] varchar(1) ,
  [INTERNETLINK] varchar(254) ,
  [FARBE] varchar(6) ,
  CONSTRAINT [PK_MAC] PRIMARY KEY ([KYMACID], [MACGO])
);
CREATE UNIQUE INDEX [K2MAC] ON [MAC] ([MACGO], [MACART], [KYMACID]);

CREATE TABLE [MACENTRY] (
  [RINFO] varchar(34) ,
  [MACID] varchar(6) ,
  [KYMACID] varchar(6) ,
  [MACGO] varchar(1) ,
  [LFDMACENTRY] varchar(3) ,
  [GOART] varchar(1) ,
  [FOLGEMACGO] varchar(1) ,
  [LSTNR] varchar(6) ,
  [FAKULTATIV] varchar(1) ,
  [KURZTEXT] varchar(60) ,
  [ANZAHL] varchar(7) ,
  [FAKTOR] varchar(6) ,
  [ZRULE] varchar(1) ,
  [PRULE] varchar(1) ,
  [TECPREISNR] varchar(1) ,
  [STDLEBID] varchar(3) ,
  [ABDINGUNG] varchar(1) ,
  CONSTRAINT [PK_MACENTRY] PRIMARY KEY ([KYMACID], [MACGO], [LFDMACENTRY])
);

CREATE TABLE [MANDANT] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [VALID] varchar(1) ,
  [ADRID] varchar(6) ,
  [KZVABRNR] varchar(10) ,
  [KVABRNR] varchar(10) ,
  [KVFORMABRNR] varchar(10) ,
  [BGABRNR] varchar(10) ,
  [GEMATIKMANDANTID] varchar(2) ,
  [PRAXISID] varchar(3) ,
  [PRAXISBEZEICHNUNG] varchar(60) ,
  [STEMPEL1] varchar(40) ,
  [STEMPEL2] varchar(40) ,
  [STEMPEL3] varchar(40) ,
  [STEMPEL4] varchar(40) ,
  [STEMPEL5] varchar(40) ,
  [STEMPEL6] varchar(40) ,
  [STEMPEL7] varchar(40) ,
  [STEMPEL8] varchar(40) ,
  [ASTEMPEL1] varchar(40) ,
  [ASTEMPEL2] varchar(40) ,
  [ASTEMPEL3] varchar(40) ,
  [ASTEMPEL4] varchar(40) ,
  [ASTEMPEL5] varchar(40) ,
  [ASTEMPEL6] varchar(40) ,
  [ASTEMPEL7] varchar(40) ,
  [ASTEMPEL8] varchar(40) ,
  [UETRAEGERDRUCK] varchar(1) ,
  [FACHGEBIET] varchar(1) ,
  [ANERKANNT] varchar(1) ,
  [DURCHGANGSARZT] varchar(1) ,
  [KLINIK] varchar(1) ,
  [MDIDOFRULEART] varchar(64) ,
  [M1K] varchar(16) ,
  [M2K] varchar(16) ,
  [M3K] varchar(16) ,
  [M4K] varchar(16) ,
  [M1P] varchar(16) ,
  [M2P] varchar(16) ,
  [M3P] varchar(16) ,
  [M4P] varchar(16) ,
  [ADRIDRA] varchar(6) ,
  [STDTECGOARTKASPAT] varchar(1) ,
  [STDTECGOARTPRIVPAT] varchar(1) ,
  [ELABUSTKEYVALID] varchar(1) ,
  [ELABUSTKEYABDATUM] varchar(8) ,
  [ELABUSTKEY] varchar(20) ,
  [MATERIALNACHWEIS] varchar(1) ,
  [PASSWORT] varchar(20) ,
  [PASSWORT2] varchar(20) ,
  [USTNUMMER] varchar(40) ,
  [USTNUMMER2] varchar(40) ,
  [USTNUMMER3] varchar(40) ,
  [GLAEUBIGERID] varchar(35) ,
  [KVDTAMITBHDKZ] varchar(1) ,
  [KVDTAMITAODT] varchar(1) ,
  [KVDTAMITKADT] varchar(1) ,
  [NEXTFORTLFDFAKT] varchar(6) ,
  [PASSWORT3] varchar(20) ,
  [PASSWORT4] varchar(20) ,
  [EXTERNID] varchar(36) ,
  [UMSMAIL] varchar(254) ,
  [UMSUSER] varchar(32) ,
  [UMSPWD] varchar(32) ,
  CONSTRAINT [PK_MANDANT] PRIMARY KEY ([MDID])
);

CREATE TABLE [MATERIALBUCH] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [BESTELLID] varchar(10) ,
  [ZUBESTELLEN] varchar(1) ,
  [ANZAHL] varchar(9) ,
  [ARTIKELNAME] varchar(40) ,
  [BESTELLNUMMER] varchar(20) ,
  [BETRAG] varchar(9) ,
  [LIEFERANTID] varchar(6) ,
  [BEMERKUNG] varchar(254) ,
  [PID] varchar(3) ,
  CONSTRAINT [PK_MATERIALBUCH] PRIMARY KEY ([MDID], [BESTELLID])
);

CREATE TABLE [MDFIBUPROFIL] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [ABDATUM] varchar(8) ,
  [BARKTO] varchar(6) ,
  [STDERLOESKTO] varchar(6) ,
  [STDPATERLOESKTO] varchar(6) ,
  [STDRZERLOESKTO] varchar(6) ,
  [STDKZVERLOESKTO] varchar(6) ,
  [STDKASERLOESKTO] varchar(6) ,
  [ELABKTO] varchar(6) ,
  [PRAXISMATKTO] varchar(6) ,
  [PORTOKTO] varchar(6) ,
  [UST1KTO] varchar(6) ,
  [UST1KEY] varchar(1) ,
  [UST2KTO] varchar(6) ,
  [UST2KEY] varchar(1) ,
  [UST3KTO] varchar(6) ,
  [UST3KEY] varchar(1) ,
  [UST4KTO] varchar(6) ,
  [UST4KEY] varchar(1) ,
  [UST5KTO] varchar(6) ,
  [UST5KEY] varchar(1) ,
  [UST6KTO] varchar(6) ,
  [UST6KEY] varchar(1) ,
  [UST7KTO] varchar(6) ,
  [UST7KEY] varchar(1) ,
  [UST8KTO] varchar(6) ,
  [UST8KEY] varchar(1) ,
  [UST9KTO] varchar(6) ,
  [UST9KEY] varchar(1) ,
  [ZAHLLASTKTO] varchar(6) ,
  [GUVKTO] varchar(6) ,
  [TRANSFERART] varchar(1) ,
  [BUCHUNGSSEQUENZ] varchar(1) ,
  [KONTENRAHMEN] varchar(1) ,
  [FIBUMODE] varchar(1) ,
  [MDFP1] varchar(80) ,
  [MDFP2] varchar(80) ,
  [DATEV1] varchar(80) ,
  [DATEV2] varchar(80) ,
  [DATEV3] varchar(80) ,
  [DATEV4] varchar(80) ,
  [UST10KTO] varchar(6) ,
  [UST10KEY] varchar(1) ,
  [UST11KTO] varchar(6) ,
  [UST11KEY] varchar(1) ,
  [UST12KTO] varchar(6) ,
  [UST12KEY] varchar(1) ,
  [UST13KTO] varchar(6) ,
  [UST13KEY] varchar(1) ,
  CONSTRAINT [PK_MDFIBUPROFIL] PRIMARY KEY ([MDID], [ABDATUM])
);

CREATE TABLE [MDPRAXISPROFIL] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [PRAXISID] varchar(3) ,
  [STEMPEL1] varchar(40) ,
  [STEMPEL2] varchar(40) ,
  [STEMPEL3] varchar(40) ,
  [STEMPEL4] varchar(40) ,
  [STEMPEL5] varchar(40) ,
  [STEMPEL6] varchar(40) ,
  [STEMPEL7] varchar(40) ,
  [STEMPEL8] varchar(40) ,
  [ASTEMPEL1] varchar(40) ,
  [ASTEMPEL2] varchar(40) ,
  [ASTEMPEL3] varchar(40) ,
  [ASTEMPEL4] varchar(40) ,
  [ASTEMPEL5] varchar(40) ,
  [ASTEMPEL6] varchar(40) ,
  [ASTEMPEL7] varchar(40) ,
  [ASTEMPEL8] varchar(40) ,
  CONSTRAINT [PK_MDPRAXISPROFIL] PRIMARY KEY ([MDID], [PRAXISID])
);

CREATE TABLE [MEDIKAMENT] (
  [RINFO] varchar(34) ,
  [KUERZEL] varchar(10) ,
  [KYKUERZEL] varchar(10) ,
  [PHARMAZENTRALNR] varchar(10) ,
  [KYPHARMAZENTRALNR] varchar(10) ,
  [ABDATUM] varchar(8) ,
  [BESCHREIBUNG] varchar(40) ,
  [PREIS] varchar(10) ,
  [NAME] varchar(40) ,
  [GROESSE] varchar(7) ,
  [FORM] varchar(4) ,
  [FACHINFO] varchar(254) ,
  [NEBENWIRKUNGEN] varchar(254) ,
  [EDITIERBAR] varchar(1) ,
  [KATEGORIE] varchar(1) ,
  [HERSTELLER] varchar(30) ,
  [DOSIERUNG] varchar(30) ,
  [ZUZAHLEINSTUF] varchar(4) ,
  CONSTRAINT [PK_MEDIKAMENT] PRIMARY KEY ([KYKUERZEL], [ABDATUM])
);
CREATE UNIQUE INDEX [K2MEDIKAMENT] ON [MEDIKAMENT] ([KYPHARMAZENTRALNR], [ABDATUM]);

CREATE TABLE [MEDIKAMENTRY] (
  [RINFO] varchar(34) ,
  [KUERZEL] varchar(10) ,
  [KYKUERZEL] varchar(10) ,
  [LFDMEDIKAMENTRY] varchar(3) ,
  [LINE] varchar(160) ,
  CONSTRAINT [PK_MEDIKAMENTRY] PRIMARY KEY ([KYKUERZEL], [LFDMEDIKAMENTRY])
);

CREATE TABLE [MESSUNG] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LFDMESSUNG] varchar(5) ,
  [ZEITSTEMPEL] varchar(14) ,
  [ZAEHNE] varchar(18) ,
  [MESSART] varchar(1) ,
  [MESSWERTE] varchar(10) ,
  [LOTID] varchar(10) ,
  [VERFALLDATUM] varchar(8) ,
  CONSTRAINT [PK_MESSUNG] PRIMARY KEY ([PATNR], [LFDMESSUNG])
);
CREATE UNIQUE INDEX [K2MESSUNG] ON [MESSUNG] ([PATNR], [MESSART], [LFDMESSUNG]);

CREATE TABLE [MODULEPOOL] (
  [RINFO] varchar(34) ,
  [MODULEID] varchar(2) ,
  [KATEGORIE] varchar(1) ,
  [MODULENAME] varchar(40) ,
  [PROGIDS1] varchar(210) ,
  [LINKZIEL] varchar(20) ,
  [LIZENZ] varchar(20) ,
  [MODULEFLAGS] varchar(20) ,
  [MODULESTATES] varchar(20) ,
  [PUBLISHINGDATE] varchar(8) ,
  [PRICE] varchar(7) ,
  [PRICEPERMONTH] varchar(7) ,
  CONSTRAINT [PK_MODULEPOOL] PRIMARY KEY ([MODULEID])
);
CREATE UNIQUE INDEX [K2MODULEPOOL] ON [MODULEPOOL] ([KATEGORIE], [MODULENAME]);

CREATE TABLE [NUMBERPOOL] (
  [RINFO] varchar(34) ,
  [NUMBERPOOLID] varchar(2) ,
  [ADRID] varchar(6) ,
  [PATNR] varchar(10) ,
  [PID] varchar(3) ,
  [MDID] varchar(2) ,
  [LEBID] varchar(3) ,
  CONSTRAINT [PK_NUMBERPOOL] PRIMARY KEY ([NUMBERPOOLID])
);

CREATE TABLE [OPS] (
  [RINFO] varchar(34) ,
  [OPSCODE] varchar(12) ,
  [KAPITEL] varchar(3) ,
  [GRUPPE] varchar(12) ,
  [KATEGORIE] varchar(8) ,
  [SCHNITTNAHTZEIT] varchar(2) ,
  [LOKALISATION] varchar(1) ,
  [ERWEITERT] varchar(1) ,
  [ZWEISTERNE] varchar(1) ,
  CONSTRAINT [PK_OPS] PRIMARY KEY ([OPSCODE])
);
CREATE UNIQUE INDEX [K2OPS] ON [OPS] ([KATEGORIE], [KAPITEL], [GRUPPE], [OPSCODE]);

CREATE TABLE [OPSENTRY] (
  [RINFO] varchar(34) ,
  [OPSCODE] varchar(12) ,
  [LFDOPSENTRY] varchar(3) ,
  [ENTRYTYP] varchar(1) ,
  [ENTRY] varchar(254) ,
  CONSTRAINT [PK_OPSENTRY] PRIMARY KEY ([OPSCODE], [LFDOPSENTRY])
);

CREATE TABLE [PABEFUND] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LFDPABEFUND] varchar(3) ,
  [KCBEFUND] varchar(36) ,
  [TASCHENTIEFED] varchar(108) ,
  [TASCHENTIEFEM] varchar(108) ,
  [TASCHENTIEFEF] varchar(108) ,
  [TASCHENTIEFEO] varchar(108) ,
  [TASCHENTIEFED2] varchar(108) ,
  [TASCHENTIEFEM2] varchar(108) ,
  [LOCKERUNGSGRAD] varchar(36) ,
  [LOCKERUNGSGRAD2] varchar(36) ,
  [ZAHNHALSHOEHE] varchar(36) ,
  [FURKATION] varchar(36) ,
  [ELONGATION] varchar(36) ,
  [REZESSION] varchar(max) ,
  [VITAL] varchar(36) ,
  [BEHGEPLANT] varchar(36) ,
  [BOP] varchar(219) ,
  [NISCHEN] varchar(32) ,
  [AVDIABETES] varchar(1) ,
  [AVVASOMOTERKRANKUNG] varchar(1) ,
  [AVMAGENDARMSTOERUNG] varchar(1) ,
  [SONSTERKRANKUNGEN] varchar(30) ,
  [SONSTERKRANKUNGEN2] varchar(30) ,
  [SONSTERKRANKUNGEN3] varchar(30) ,
  [SONSTERKRANKUNGEN4] varchar(30) ,
  [GINGIVITIS] varchar(1) ,
  [SVZAHNFLEISCHBLUTEN] varchar(1) ,
  [SVZAHNBELAG] varchar(1) ,
  [SVZAHNWANDERUNG] varchar(1) ,
  [SVZAHNVERLUSTDLOCK] varchar(1) ,
  [SVKIEFERBEHANDLUNG] varchar(1) ,
  [SVZAHNFLEISCHJAHR] varchar(4) ,
  [PFKNIRSCHEN] varchar(1) ,
  [PFPRESSEN] varchar(1) ,
  [PFLIPPENPRESSEN] varchar(1) ,
  [PFZUNGENPRESSEN] varchar(1) ,
  [PFABRASIONEN] varchar(1) ,
  [PFSONST] varchar(20) ,
  [ZEHERAUSNEHMBAR] varchar(1) ,
  [ZEHERAUSNEHMBARSEIT] varchar(4) ,
  [ZEFESTSITZEND] varchar(1) ,
  [ZEFESTSITZENDSEIT] varchar(4) ,
  [MPENTZUENDGENERELL] varchar(1) ,
  [MPENTZUENDLOKAL] varchar(1) ,
  [MPTASCHENSEKRETION] varchar(1) ,
  [MPKONKREMENTE] varchar(1) ,
  [DIAGNOSE1] varchar(30) ,
  [DIAGNOSE2] varchar(30) ,
  [DIAGNOSE3] varchar(30) ,
  [DIAGNOSE4] varchar(30) ,
  [DIAGNOSE5] varchar(30) ,
  [DIAGNOSE6] varchar(30) ,
  [PASTATUS] varchar(32) ,
  [APIPBI] varchar(64) ,
  [BEFDATUM] varchar(8) ,
  [VORLFDPABEFUND] varchar(3) ,
  [ABRDATUM] varchar(8) ,
  [IMPLANTATART] varchar(72) ,
  [BEHPATWUNSCH] varchar(36) ,
  CONSTRAINT [PK_PABEFUND] PRIMARY KEY ([PATNR], [LFDPABEFUND])
);

CREATE TABLE [PARHIT] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [PATNR] varchar(10) ,
  [LFDPATBILL] varchar(5) ,
  [ABRART] varchar(1) ,
  [GLFDPATVD] varchar(3) ,
  [GLFDFAKT] varchar(5) ,
  [LFDPLAN] varchar(3) ,
  [PRUEFCODE] varchar(160) ,
  [ABRSTATUS] varchar(1) ,
  [DTADATUM] varchar(8) ,
  [VERSICHERTENNR] varchar(12) ,
  [PATTITEL] varchar(28) ,
  [PATVORNAME] varchar(28) ,
  [KYPATVORNAME] varchar(28) ,
  [PATAPPENDIX] varchar(15) ,
  [PATNAME] varchar(28) ,
  [KYPATNAME] varchar(28) ,
  [PATPLZ] varchar(7) ,
  [PATORT] varchar(23) ,
  [PATGEBDATUM] varchar(8) ,
  [PATWLC] varchar(3) ,
  [PATSEX] varchar(1) ,
  [PATVORSATZ] varchar(20) ,
  [Z1KASKUERZEL] varchar(10) ,
  [VNACHWEIS] varchar(1) ,
  [EINLESEDATUM] varchar(8) ,
  [BKVKASNAME] varchar(30) ,
  [BKVKASNR] varchar(12) ,
  [ZUSTKZV] varchar(5) ,
  [MFRDIG] varchar(1) ,
  [RSADIG] varchar(3) ,
  [RSAART] varchar(1) ,
  [WSO] varchar(1) ,
  [GUELTIGABDATUM] varchar(8) ,
  [GUELTIGBISDATUM] varchar(8) ,
  [DTABEMERKUNG] varchar(254) ,
  [PM] varchar(1) ,
  [KZVINTERN] varchar(254) ,
  [AZSOKTR] varchar(50) ,
  [PASTATUS] varchar(max) ,
  [PLANUNGSDATUM] varchar(8) ,
  [GUTACHTERDATUM] varchar(8) ,
  [BEHENDE] varchar(8) ,
  [KZGUTACHTER] varchar(1) ,
  [THERAPIEERG] varchar(1) ,
  [SUMTOTAL] varchar(10) ,
  [VERSART] varchar(1) ,
  [SONSTFALLKZ] varchar(1) ,
  [PASONST1] varchar(80) ,
  [PABEMERKUNGEN] varchar(max) ,
  [ANTRAGSNUMMER] varchar(80) ,
  CONSTRAINT [PK_PARHIT] PRIMARY KEY ([MDID], [PATNR], [LFDPLAN], [LFDPATBILL])
);
CREATE UNIQUE INDEX [K2PARHIT] ON [PARHIT] ([MDID], [DTADATUM], [KYPATNAME], [KYPATVORNAME], [PATNR], [LFDPLAN], [LFDPATBILL]);

CREATE TABLE [PARHITLST] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [PATNR] varchar(10) ,
  [LFDPLAN] varchar(3) ,
  [LFDLST] varchar(3) ,
  [PRUEFCODE] varchar(3) ,
  [GEBART] varchar(1) ,
  [LSTNR] varchar(6) ,
  [ANZVERS] varchar(5) ,
  [KZVINTERN] varchar(254) ,
  [LFDPATBILL] varchar(5) ,
  [LSTDATUM] varchar(8) ,
  [LSTSITZUNG] varchar(1) ,
  [DATLASTLST] varchar(8) ,
  CONSTRAINT [PK_PARHITLST] PRIMARY KEY ([MDID], [PATNR], [LFDPLAN], [LFDLST])
);

CREATE TABLE [PARPOOL] (
  [RINFO] varchar(34) ,
  [PROGID] varchar(3) ,
  [KUERZEL] varchar(12) ,
  [PARVALUE] varchar(254) ,
  CONSTRAINT [PK_PARPOOL] PRIMARY KEY ([PROGID], [KUERZEL])
);

CREATE TABLE [PARSTATUS] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [DATUM] varchar(8) ,
  [PARJAHRVORHER] varchar(4) ,
  [SONST] varchar(254) ,
  [PARODONTITIS] varchar(1) ,
  [PARSYSTEMISCH] varchar(254) ,
  [STADIUM] varchar(1) ,
  [RKA] varchar(1) ,
  [CAL] varchar(1) ,
  [ZAHNVERLUST] varchar(1) ,
  [KOMPFAKTOR] varchar(1) ,
  [VERTEILUNG] varchar(1) ,
  [GRAD] varchar(1) ,
  [KAI] varchar(1) ,
  [DIABETES] varchar(1) ,
  [RAUCHEN] varchar(1) ,
  CONSTRAINT [PK_PARSTATUS] PRIMARY KEY ([PATNR], [DATUM])
);

CREATE TABLE [PAT] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LPATNR] varchar(20) ,
  [KYLPATNR] varchar(20) ,
  [ABDATUM] varchar(8) ,
  [PATNAME] varchar(28) ,
  [KYPATNAME] varchar(28) ,
  [PATVORNAME] varchar(28) ,
  [KYPATVORNAME] varchar(28) ,
  [ADRIDP] varchar(6) ,
  [ADRIDR] varchar(6) ,
  [ADRIDA] varchar(6) ,
  [ADRIDK] varchar(6) ,
  [ADRIDU] varchar(6) ,
  [ADRIDW] varchar(6) ,
  [ADRIDH] varchar(6) ,
  [ADRIDC] varchar(6) ,
  [EPATNR] varchar(10) ,
  [GEBDATUM] varchar(8) ,
  [PKNRBW] varchar(20) ,
  [EINTRDATUM] varchar(8) ,
  [ANAMNESE] varchar(80) ,
  [GROESSE] varchar(3) ,
  [GEWICHT] varchar(3) ,
  [HAARFARBE] varchar(20) ,
  [SONST1] varchar(80) ,
  [SONST2] varchar(80) ,
  [M1MAHNDELAY] varchar(2) ,
  [RECALLARTREITER] varchar(40) ,
  [RECALLITVREITER] varchar(40) ,
  [LASTRECALLDATUM] varchar(8) ,
  [BENACHRICHTIGUNG] varchar(1) ,
  [BESTWOCHENTAG] varchar(6) ,
  [BESTABZEIT] varchar(24) ,
  [BESTBISZEIT] varchar(24) ,
  [LASTBEHDATUM] varchar(8) ,
  [LAST01DATUM] varchar(8) ,
  [LASTMED1DATUM] varchar(8) ,
  [LASTACCESS] varchar(17) ,
  [LASTPATBEFRAGUNG] varchar(80) ,
  [LASTEINVRZ] varchar(110) ,
  [VERSTORBENAM] varchar(8) ,
  [GESPERRT] varchar(1) ,
  [LOCKWORKSTATION] varchar(3) ,
  [LOCKINSTANZ] varchar(1) ,
  [LOCKZEITPUNKT] varchar(17) ,
  [SYNCHRONFLAG] varchar(1) ,
  [LASTLINE] varchar(2) ,
  [LASTPAGE] varchar(2) ,
  [LASTDATE] varchar(8) ,
  [EINTRPRAXISID] varchar(3) ,
  [STAMMLEBID] varchar(3) ,
  [IPLEBID] varchar(3) ,
  [PKVFAKTOR] varchar(6) ,
  [BONUSZUSCHFAKTORZE] varchar(3) ,
  [STDZUSCHFAKTORKFO] varchar(3) ,
  [TECGOART] varchar(1) ,
  [TECPREISNR] varchar(1) ,
  [VXPATIENTUID] varchar(40) ,
  [VXPATIENTNUMBER] varchar(25) ,
  [PRIVADISAA] varchar(150) ,
  [EPAADMINISTRATION] varchar(254) ,
  [ADHOCEXPIRATIONDATE] varchar(110) ,
  [EXTERNID] varchar(36) ,
  [PATBEZIEHUNGEN] varchar(max) ,
  [EMOJI] varchar(100) ,
  CONSTRAINT [PK_PAT] PRIMARY KEY ([PATNR])
);
CREATE UNIQUE INDEX [K2PAT] ON [PAT] ([KYPATNAME], [KYPATVORNAME], [PATNR]);
CREATE INDEX [K3PAT] ON [PAT] ([KYLPATNR]);
CREATE INDEX [K4PAT] ON [PAT] ([VXPATIENTUID]);

CREATE TABLE [PATINFO] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [DATUM] varchar(8) ,
  [LFDPATINFOART] varchar(4) ,
  [LEBID] varchar(3) ,
  [ART] varchar(1) ,
  [INFORMATION] varchar(80) ,
  [LFDANAMNESE] varchar(3) ,
  [LFDFREITEXT] varchar(3) ,
  [LFDANAMVERSION] varchar(2) ,
  [MDID] varchar(2) ,
  [FRAGEBOGENART] varchar(1) ,
  [LFDFRAGEBOGEN] varchar(3) ,
  [LFDFRAGEBOGENENTRY] varchar(3) ,
  [STATUS] varchar(1) ,
  [TERMIN] varchar(1) ,
  [FARBE] varchar(6) ,
  [PLANUNGSART] varchar(50) ,
  [PID] varchar(3) ,
  CONSTRAINT [PK_PATINFO] PRIMARY KEY ([PATNR], [DATUM], [LFDPATINFOART], [ART])
);
CREATE UNIQUE INDEX [K2PATINFO] ON [PATINFO] ([PATNR], [ART], [DATUM], [LFDPATINFOART]);

CREATE TABLE [PERSONAL] (
  [RINFO] varchar(34) ,
  [PID] varchar(3) ,
  [VALID] varchar(1) ,
  [PASSWORT] varchar(20) ,
  [KUERZEL] varchar(6) ,
  [PASSWORTSTUFE] varchar(1) ,
  [RECHTEID] varchar(2) ,
  [FACHGEBIET] varchar(1) ,
  [ADRID] varchar(6) ,
  [ICCSN] varchar(20) ,
  [PASSWORTDATUM] varchar(8) ,
  [PROUSERID] varchar(40) ,
  [PRAXISID] varchar(3) ,
  [GEMATIKUSERID] varchar(36) ,
  [GEMATIKWORKPLACEID] varchar(3) ,
  [EXTERNID] varchar(36) ,
  [CDPV3USERID] varchar(254) ,
  [CDPV3SSOKEY] varchar(254) ,
  [TELEMATIKID] varchar(128) ,
  [GEMATIKVORNAME] varchar(45) ,
  [GEMATIKNAME] varchar(45) ,
  [CINFO] varchar(34) ,
  CONSTRAINT [PK_PERSONAL] PRIMARY KEY ([PID])
);
CREATE UNIQUE INDEX [K2PERSONAL] ON [PERSONAL] ([KUERZEL]);

CREATE TABLE [PRAXIS] (
  [RINFO] varchar(34) ,
  [PRAXISID] varchar(3) ,
  [PRAXISNAME] varchar(60) ,
  [STAMMLEBLIQ] varchar(1) ,
  [KZVNR] varchar(2) ,
  [KVNR] varchar(2) ,
  [VSPID] varchar(2) ,
  [KUNDENNR] varchar(6) ,
  [LANDKUERZEL] varchar(3) ,
  [LANDSPRACHE] varchar(4) ,
  [DBRELEASE] varchar(3) ,
  [UPDATUM] varchar(8) ,
  [ISELAB] varchar(5) ,
  [PRAXISTYP] varchar(1) ,
  [EXTERNPRAXISID] varchar(5) ,
  [BSNR] varchar(9) ,
  [UEBAGART] varchar(1) ,
  [UEBAGKZVNR] varchar(2) ,
  [UEBAGKBRPAR] varchar(1) ,
  [UEBAGLESEN] varchar(1) ,
  [UEBAGLFDNR] varchar(3) ,
  [VITAXDATEN] varchar(254) ,
  [CDPV3LOCATIONID] varchar(100) ,
  [ADRID] varchar(6) ,
  CONSTRAINT [PK_PRAXIS] PRIMARY KEY ([PRAXISID])
);

CREATE TABLE [PRINTER] (
  [RINFO] varchar(34) ,
  [LFDWORKSTATION] varchar(3) ,
  [LFDPRINTER] varchar(3) ,
  [BESCHREIBUNG] varchar(30) ,
  [PORT] varchar(1) ,
  [EXPORTFNAME] varchar(64) ,
  [PRINTSERVER] varchar(30) ,
  [PRINTQUEUE] varchar(64) ,
  [GLOBALTOPMARG] varchar(7) ,
  [GLOBALLEFTMARG] varchar(7) ,
  [PRINTERCLASS] varchar(1) ,
  [ANZSCHAECHTE] varchar(1) ,
  [SECONDSPERPAGE] varchar(3) ,
  [YZOOM] varchar(7) ,
  [XZOOM] varchar(7) ,
  [PRINTMETHOD] varchar(1) ,
  CONSTRAINT [PK_PRINTER] PRIMARY KEY ([LFDWORKSTATION], [LFDPRINTER])
);

CREATE TABLE [PROGPOOL] (
  [RINFO] varchar(34) ,
  [PROGNAME] varchar(30) ,
  [KYPROGNAME] varchar(30) ,
  [PROGID] varchar(3) ,
  [LIZENZ] varchar(9) ,
  [DEMOLIZENZ] varchar(9) ,
  [MINPASSWORTSTUFE] varchar(1) ,
  [RECHTEEDITIERBAR] varchar(1) ,
  [EXKLUSIV] varchar(1) ,
  [LOCKWORKSTATION] varchar(3) ,
  [LOCKINSTANZ] varchar(1) ,
  [LOCKZEITPUNKT] varchar(17) ,
  [BUSY] varchar(3) ,
  [ANZCALLS] varchar(9) ,
  [TESTMODUS] varchar(1) ,
  [PROTOKOLLDATEI] varchar(20) ,
  [RESULTS] varchar(40) ,
  [PERSONENBEZUG] varchar(1) ,
  CONSTRAINT [PK_PROGPOOL] PRIMARY KEY ([PROGID])
);
CREATE UNIQUE INDEX [K2PROGPOOL] ON [PROGPOOL] ([KYPROGNAME]);

CREATE TABLE [PROTOKOLL] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [ART] varchar(1) ,
  [SUBART] varchar(1) ,
  [INFO] varchar(20) ,
  [BESCHREIBUNG] varchar(80) ,
  CONSTRAINT [PK_PROTOKOLL] PRIMARY KEY ([RINFO])
);
CREATE UNIQUE INDEX [K2PROTOKOLL] ON [PROTOKOLL] ([ART], [RINFO]);

CREATE TABLE [PRUEFNACHWEIS] (
  [RINFO] varchar(34) ,
  [GEMATIKMANDANTID] varchar(2) ,
  [PATNR] varchar(10) ,
  [QUARTAL] varchar(5) ,
  [ICCSN] varchar(20) ,
  [LFDPRUEFNACHWEIS] varchar(2) ,
  [CDMVERSION] varchar(10) ,
  [ZEITSTEMPEL] varchar(14) ,
  [ERGEBNIS] varchar(1) ,
  [ERRORCODE] varchar(5) ,
  [PRUEFZIFFER] varchar(128) ,
  [EGKVSD] varchar(max) ,
  [ICCSNSMCB] varchar(20) ,
  CONSTRAINT [PK_PRUEFNACHWEIS] PRIMARY KEY ([GEMATIKMANDANTID], [PATNR], [QUARTAL], [ICCSN], [LFDPRUEFNACHWEIS])
);

CREATE TABLE [PUNKTWERTE] (
  [RINFO] varchar(34) ,
  [PWGROUP] varchar(10) ,
  [PWLART] varchar(1) ,
  [ABDATUM] varchar(8) ,
  [PWWEST] varchar(9) ,
  [PWOST] varchar(9) ,
  [PWGUTACHTER] varchar(9) ,
  [VERSANDPAUSCHALE] varchar(7) ,
  CONSTRAINT [PK_PUNKTWERTE] PRIMARY KEY ([PWGROUP], [PWLART], [ABDATUM])
);

CREATE TABLE [PWGROUPS] (
  [RINFO] varchar(34) ,
  [PWGROUP] varchar(10) ,
  [SYSTEM] varchar(1) ,
  [BESCHREIBUNG] varchar(30) ,
  [BKVREF] varchar(10) ,
  CONSTRAINT [PK_PWGROUPS] PRIMARY KEY ([PWGROUP])
);

CREATE TABLE [QAHIT] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [LFDFALL] varchar(5) ,
  [PATNR] varchar(10) ,
  [LFDPATBILL] varchar(5) ,
  [ABRART] varchar(1) ,
  [ABRPERDTA] varchar(1) ,
  [GLFDPATVD] varchar(3) ,
  [GKTRAEGER] varchar(1) ,
  [GLFDFAKT] varchar(5) ,
  [SLFDFAKT] varchar(5) ,
  [VONDATUM] varchar(8) ,
  [BISDATUM] varchar(8) ,
  [SUCHLAUFQYY] varchar(3) ,
  [LFDPATFALL] varchar(1) ,
  [BMIPOS] varchar(8) ,
  [BMILEN] varchar(5) ,
  [DTASORTKEY] varchar(24) ,
  [PATTITEL] varchar(28) ,
  [PATVORNAME] varchar(28) ,
  [PATAPPENDIX] varchar(15) ,
  [PATNAME] varchar(28) ,
  [PATSTRASSE] varchar(30) ,
  [PATPLZ] varchar(7) ,
  [PATORT] varchar(23) ,
  [PATGEBDATUM] varchar(8) ,
  [Z1KASKUERZEL] varchar(10) ,
  [VNACHWEIS] varchar(1) ,
  [BEHINDERT] varchar(1) ,
  [EINLESEDATUM] varchar(8) ,
  [KVKKASNAME] varchar(28) ,
  [KVKKASNR] varchar(9) ,
  [VERSICHERTENNR] varchar(12) ,
  [MFRDIG] varchar(1) ,
  [RSA] varchar(3) ,
  [WSO] varchar(1) ,
  [GUELTIGBISDATUM] varchar(8) ,
  [CHECKSTATUS] varchar(80) ,
  [LSTUNBEKANNT] varchar(60) ,
  [DRUCKSTATUS] varchar(1) ,
  [PWKC] varchar(9) ,
  [PWIP] varchar(9) ,
  [PWKFO] varchar(9) ,
  [PKTSUMKC] varchar(6) ,
  [PKTSUMIP] varchar(6) ,
  [PKTSUMKFO] varchar(6) ,
  [ZAHONORAR] varchar(10) ,
  [SUMELAB] varchar(10) ,
  [SUMPMAT] varchar(10) ,
  [SUMFLAB] varchar(10) ,
  [SUMTOTAL] varchar(10) ,
  [DTA1] varchar(80) ,
  [DTA2] varchar(80) ,
  [DTA3] varchar(80) ,
  [DTA4] varchar(80) ,
  CONSTRAINT [PK_QAHIT] PRIMARY KEY ([MDID], [LFDFALL])
);
CREATE UNIQUE INDEX [K2QAHIT] ON [QAHIT] ([MDID], [DTASORTKEY]);

CREATE TABLE [QUAMADOKU] (
  [RINFO] varchar(34) ,
  [PROGID] varchar(3) ,
  [LFDWORKSTATION] varchar(3) ,
  [LFDDOKU] varchar(2) ,
  [KATEGORIE] varchar(1) ,
  [TITEL] varchar(254) ,
  [LINKZIEL] varchar(254) ,
  CONSTRAINT [PK_QUAMADOKU] PRIMARY KEY ([PROGID], [LFDWORKSTATION], [LFDDOKU])
);

CREATE TABLE [RECHTE] (
  [RINFO] varchar(34) ,
  [RECHTEID] varchar(2) ,
  [KYRECHTEID] varchar(2) ,
  [BESCHREIBUNG] varchar(50) ,
  [PROGIDS1] varchar(210) ,
  [PROGIDS2] varchar(210) ,
  [PROGIDS3] varchar(210) ,
  [PROGIDS4] varchar(210) ,
  [PERMISSION1] varchar(70) ,
  [PERMISSION2] varchar(70) ,
  [PERMISSION3] varchar(70) ,
  [PERMISSION4] varchar(70) ,
  CONSTRAINT [PK_RECHTE] PRIMARY KEY ([KYRECHTEID])
);

CREATE TABLE [REMARK] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [PLANART] varchar(1) ,
  [LFDBEFUND] varchar(3) ,
  [REMARKART] varchar(1) ,
  [LFDREMARK] varchar(3) ,
  [BESCHREIBUNG] varchar(160) ,
  CONSTRAINT [PK_REMARK] PRIMARY KEY ([PATNR], [PLANART], [LFDBEFUND], [REMARKART], [LFDREMARK])
);

CREATE TABLE [REZEPT] (
  [RINFO] varchar(34) ,
  [DATUM] varchar(8) ,
  [LFDREZEPT] varchar(4) ,
  [Z1KASKUERZEL] varchar(10) ,
  [MDID] varchar(2) ,
  [PATNR] varchar(10) ,
  [QUARTAL] varchar(5) ,
  [VERORDNUNG] varchar(254) ,
  [PRIVATREZEPT] varchar(1) ,
  [MEDREZEPT] varchar(1) ,
  [ICD] varchar(80) ,
  [BTMREZEPTNUMMER] varchar(9) ,
  [LEBID] varchar(3) ,
  [REZEPTSONST] varchar(max) ,
  [DOKUMENTENID1] varchar(36) ,
  [DOKUMENTENID2] varchar(36) ,
  [REZEPTSTATUS] varchar(1) ,
  [SIGNATUR] varchar(1) ,
  [STORNODATUM] varchar(8) ,
  [VERSANDDATUM1] varchar(14) ,
  [VERSANDDATUM2] varchar(14) ,
  [LEBID2] varchar(3) ,
  [EPAUNIQUEID] varchar(64) ,
  [VERSANDDATUM3] varchar(14) ,
  [LFDNR] varchar(8) ,
  CONSTRAINT [PK_REZEPT] PRIMARY KEY ([DATUM], [LFDREZEPT])
);

CREATE TABLE [REZEPTUR] (
  [RINFO] varchar(34) ,
  [LFDREZEPTUR] varchar(4) ,
  [REZEPTURNAME] varchar(70) ,
  [KYREZEPTURNAME] varchar(70) ,
  [GESAMTMENGE] varchar(7) ,
  [GESAMTMENGEEINHEIT] varchar(12) ,
  [HERSTELLUNG] varchar(60) ,
  [VERPACKUNG] varchar(90) ,
  [GEBRAUCHSANWEISUNG] varchar(60) ,
  CONSTRAINT [PK_REZEPTUR] PRIMARY KEY ([LFDREZEPTUR])
);
CREATE INDEX [K2REZEPTUR] ON [REZEPTUR] ([KYREZEPTURNAME]);

CREATE TABLE [REZEPTURENTRY] (
  [RINFO] varchar(34) ,
  [LFDREZEPTUR] varchar(4) ,
  [LFDREZEPTURENTRY] varchar(2) ,
  [NAME] varchar(60) ,
  [PHARMAZENTRALNR] varchar(10) ,
  [DARREICHUNGSFORM] varchar(30) ,
  [MENGE] varchar(15) ,
  [MENGEEINHEIT] varchar(15) ,
  [MENGEFREITEXT] varchar(20) ,
  CONSTRAINT [PK_REZEPTURENTRY] PRIMARY KEY ([LFDREZEPTUR], [LFDREZEPTURENTRY])
);

CREATE TABLE [ROEBEFUND] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LFDROEBEFUND] varchar(3) ,
  [GRAVIDITAET] varchar(1) ,
  [ANZAHL] varchar(2) ,
  [GERAETEID] varchar(5) ,
  [BELICHTUNG] varchar(30) ,
  [XRAYMS] varchar(9) ,
  [XRAYCURRENT] varchar(6) ,
  [XRAYVOLTAGE] varchar(6) ,
  [INDIKATIONSGRUND] varchar(30) ,
  [BEMERKUNG] varchar(30) ,
  [LASTROEDATUM] varchar(8) ,
  [LASTROEREGIO] varchar(30) ,
  [LASTROEPASSDRUCK] varchar(8) ,
  [LFDNR] varchar(10) ,
  [PRAXISID] varchar(3) ,
  CONSTRAINT [PK_ROEBEFUND] PRIMARY KEY ([PATNR], [LFDROEBEFUND])
);
CREATE INDEX [K2ROEBEFUND] ON [ROEBEFUND] ([LFDNR]);

CREATE TABLE [ROOM] (
  [RINFO] varchar(34) ,
  [ROOM] varchar(1) ,
  [BESCHREIBUNG] varchar(20) ,
  CONSTRAINT [PK_ROOM] PRIMARY KEY ([ROOM])
);

CREATE TABLE [SBBESTELLENTRY] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [LFDBESTELLUNG] varchar(6) ,
  [LFDBESTELLENTRY] varchar(3) ,
  [PHARMAZENTRALNR] varchar(10) ,
  [ANZAHL] varchar(3) ,
  CONSTRAINT [PK_SBBESTELLENTRY] PRIMARY KEY ([MDID], [LFDBESTELLUNG], [LFDBESTELLENTRY])
);

CREATE TABLE [SBBESTELLUNG] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [LFDBESTELLUNG] varchar(6) ,
  [DATUM] varchar(8) ,
  [ADRID] varchar(6) ,
  [LEBID] varchar(3) ,
  CONSTRAINT [PK_SBBESTELLUNG] PRIMARY KEY ([MDID], [LFDBESTELLUNG])
);

CREATE TABLE [SCHNITTSTELLEN] (
  [RINFO] varchar(34) ,
  [TYP] varchar(1) ,
  [MDID] varchar(2) ,
  [VERTRAGSDATUM] varchar(8) ,
  [KUNDENNR] varchar(254) ,
  [ZUSATZ1] varchar(254) ,
  [ZUSATZ2] varchar(254) ,
  [STARTSAMMLUNG] varchar(8) ,
  CONSTRAINT [PK_SCHNITTSTELLEN] PRIMARY KEY ([TYP], [MDID])
);

CREATE TABLE [SELECTPOOL] (
  [RINFO] varchar(34) ,
  [LANDSPRACHE] varchar(4) ,
  [SELECTID] varchar(20) ,
  [ENTRYID] varchar(4) ,
  [TEXT10] varchar(10) ,
  [TEXT20] varchar(20) ,
  [TEXT40] varchar(40) ,
  [TEXT80] varchar(80) ,
  CONSTRAINT [PK_SELECTPOOL] PRIMARY KEY ([LANDSPRACHE], [SELECTID], [ENTRYID])
);
CREATE UNIQUE INDEX [K2SELECTPOOL] ON [SELECTPOOL] ([SELECTID], [ENTRYID], [LANDSPRACHE]);

CREATE TABLE [STERIBUCH] (
  [RINFO] varchar(34) ,
  [GERAETEID] varchar(5) ,
  [LFDNR] varchar(6) ,
  [DATUM] varchar(8) ,
  [HALTBARKEIT] varchar(8) ,
  [DAUER] varchar(3) ,
  [KONTROLLFRIST] varchar(8) ,
  [PID] varchar(3) ,
  [BEMERKUNG] varchar(254) ,
  CONSTRAINT [PK_STERIBUCH] PRIMARY KEY ([GERAETEID], [LFDNR])
);

CREATE TABLE [TB] (
  [RINFO] varchar(34) ,
  [TBGROUPID] varchar(1) ,
  [TBGROUPMEMBERID] varchar(1) ,
  [KUERZEL] varchar(8) ,
  [KYKUERZEL] varchar(8) ,
  [ICDCODE] varchar(5) ,
  [KYICDCODE] varchar(5) ,
  [PHARMAZENTRALNR] varchar(10) ,
  [MAKRO] varchar(1) ,
  [TBART] varchar(1) ,
  [BESCHREIBUNG] varchar(40) ,
  [FARBE] varchar(6) ,
  CONSTRAINT [PK_TB] PRIMARY KEY ([TBGROUPID], [TBGROUPMEMBERID], [KYKUERZEL])
);
CREATE UNIQUE INDEX [K2TB] ON [TB] ([KYKUERZEL]);
CREATE UNIQUE INDEX [K3TB] ON [TB] ([KYICDCODE], [KYKUERZEL]);

CREATE TABLE [TBENTRY] (
  [RINFO] varchar(34) ,
  [KUERZEL] varchar(8) ,
  [KYKUERZEL] varchar(8) ,
  [LFDTBENTRY] varchar(3) ,
  [LINE] varchar(160) ,
  CONSTRAINT [PK_TBENTRY] PRIMARY KEY ([KYKUERZEL], [LFDTBENTRY])
);

CREATE TABLE [TSEBON] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [KBKTO] varchar(6) ,
  [BONID] varchar(10) ,
  [ZEITSTEMPEL] varchar(14) ,
  [BONTYP] varchar(1) ,
  [TSENR] varchar(3) ,
  [TSETRANSAKTION] varchar(10) ,
  [LFDBUCHUNG] varchar(5) ,
  [BONBETRAG] varchar(13) ,
  CONSTRAINT [PK_TSEBON] PRIMARY KEY ([MDID], [KBKTO], [BONID])
);
CREATE UNIQUE INDEX [K2TSEBON] ON [TSEBON] ([MDID], [KBKTO], [ZEITSTEMPEL], [BONID]);
CREATE UNIQUE INDEX [K3TSEBON] ON [TSEBON] ([MDID], [KBKTO], [TSENR], [BONID]);

CREATE TABLE [VDESC] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LFDPATVD] varchar(3) ,
  [VDABDATUM] varchar(8) ,
  [VDBISDATUM] varchar(8) ,
  [INVALID] varchar(1) ,
  [LFALLNR] varchar(20) ,
  [KYLFALLNR] varchar(20) ,
  [Z1KASKUERZEL] varchar(10) ,
  [VNACHWEIS] varchar(1) ,
  [VNACHWEISFIRST] varchar(1) ,
  [KSART] varchar(1) ,
  [UNFALL] varchar(1) ,
  [BEHINDERT] varchar(1) ,
  [FREIWILLIG] varchar(1) ,
  [KLINIKABSCHLAG] varchar(1) ,
  [EINLESEDATUM] varchar(8) ,
  [EINLESEDATUMFIRST] varchar(8) ,
  [EINLESEUHRZEIT] varchar(4) ,
  [MOBILDEVICEID] varchar(40) ,
  [VERSICHERTENTEMPLATE] varchar(1) ,
  [KVKKASNAME] varchar(28) ,
  [KVKKASNR] varchar(9) ,
  [VKNR] varchar(5) ,
  [VERSICHERTENNR] varchar(12) ,
  [KYVERSICHERTENNR] varchar(12) ,
  [MFRDIG] varchar(1) ,
  [RSA] varchar(3) ,
  [WSO] varchar(1) ,
  [WSOERGAENZUNG] varchar(2) ,
  [TITEL] varchar(28) ,
  [VORNAME] varchar(28) ,
  [NAMENSZUSATZ] varchar(15) ,
  [NAME] varchar(28) ,
  [GEBDATUM] varchar(8) ,
  [STRASSE] varchar(30) ,
  [WOHNSITZLAENDERCODE] varchar(3) ,
  [PLZ] varchar(7) ,
  [ORT] varchar(23) ,
  [GUELTIGBISDATUM] varchar(8) ,
  [EGKVSD] varchar(max) ,
  [BKTABRVKNR] varchar(5) ,
  [BKTABRKASNAME] varchar(30) ,
  [STATIONAEREBEHVONBIS] varchar(16) ,
  [UEBERWEISERADRID] varchar(6) ,
  [UEBERWEISERDATEN] varchar(254) ,
  [UEBERWEISERDATEN2] varchar(254) ,
  [UEBERWEISERDATEN3] varchar(254) ,
  [KENNZIFFEROI] varchar(6) ,
  [KENNZIFFEROIII] varchar(6) ,
  [AUTOABRNR] varchar(60) ,
  [GEBUEHRENBEFREITBIS] varchar(8) ,
  [PSYCHOBEWILLIGTDATUM] varchar(8) ,
  [PSYCHOABKLAERUNG] varchar(1) ,
  [PSYCHOSONST] varchar(max) ,
  [SKTZUSATZANGABEN] varchar(80) ,
  [SKTZUSATZANGABEN2] varchar(80) ,
  [SKTBEMERKUNGEN] varchar(240) ,
  [CINFO] varchar(34) ,
  [EXTERNID] varchar(36) ,
  [KSSONST] varchar(1) ,
  CONSTRAINT [PK_VDESC] PRIMARY KEY ([PATNR], [LFDPATVD])
);
CREATE INDEX [K2VDESC] ON [VDESC] ([KYVERSICHERTENNR]);
CREATE INDEX [K3VDESC] ON [VDESC] ([PATNR], [VDABDATUM]);

CREATE TABLE [VDESCENTRY] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LFDPATVD] varchar(3) ,
  [LFDVDESCENTRY] varchar(3) ,
  [DATUM] varchar(8) ,
  [ART] varchar(1) ,
  [ENTRY] varchar(254) ,
  CONSTRAINT [PK_VDESCENTRY] PRIMARY KEY ([PATNR], [LFDPATVD], [LFDVDESCENTRY])
);

CREATE TABLE [WARTELISTE] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [STATUS] varchar(1) ,
  [TERMINVON] varchar(4) ,
  [TERMINBIS] varchar(4) ,
  [LEISTUNG] varchar(20) ,
  [LEISTUNG2] varchar(10) ,
  [LEBID] varchar(3) ,
  [ROOM] varchar(1) ,
  [KOMMT] varchar(4) ,
  [STANDORT] varchar(15) ,
  [NOTIZ] varchar(254) ,
  [DATUM] varchar(8) ,
  CONSTRAINT [PK_WARTELISTE] PRIMARY KEY ([PATNR])
);
CREATE INDEX [K2WARTELISTE] ON [WARTELISTE] ([KOMMT]);

CREATE TABLE [WIRKSTOFF] (
  [RINFO] varchar(34) ,
  [WIRKSTOFFNUMMER] varchar(5) ,
  [WIRKSTOFFNAME] varchar(80) ,
  [KYWIRKSTOFFNAME] varchar(80) ,
  [WIRKSTAERKE] varchar(15) ,
  [WIRKSTAERKEEINHEIT] varchar(15) ,
  CONSTRAINT [PK_WIRKSTOFF] PRIMARY KEY ([KYWIRKSTOFFNAME])
);
CREATE INDEX [K2WIRKSTOFF] ON [WIRKSTOFF] ([WIRKSTOFFNUMMER]);

CREATE TABLE [WORKFLOW] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LFDWORKFLOW] varchar(3) ,
  [BEZEICHNUNG] varchar(80) ,
  [ANLAGEPID] varchar(3) ,
  [ANLAGEDATUM] varchar(8) ,
  [LEBID] varchar(3) ,
  [BEMERKUNG] varchar(254) ,
  [WORKFLOWSTATUS] varchar(1) ,
  [NUMSTEPS] varchar(2) ,
  [AKTSTEP] varchar(2) ,
  [AKTPID] varchar(3) ,
  [PREVSTEPDATUM] varchar(8) ,
  [LFDPLAN] varchar(3) ,
  [LOCKWORKSTATION] varchar(3) ,
  [LOCKINSTANZ] varchar(1) ,
  [LOCKZEITPUNKT] varchar(17) ,
  [AKTPRIO] varchar(1) ,
  CONSTRAINT [PK_WORKFLOW] PRIMARY KEY ([PATNR], [LFDWORKFLOW])
);
CREATE UNIQUE INDEX [K2WORKFLOW] ON [WORKFLOW] ([AKTPID], [WORKFLOWSTATUS], [PATNR], [LFDWORKFLOW]);

CREATE TABLE [WORKSTATION] (
  [RINFO] varchar(34) ,
  [LFDWORKSTATION] varchar(3) ,
  [BESCHREIBUNG] varchar(50) ,
  [BEZEICHNUNG] varchar(20) ,
  [NETNODENR] varchar(10) ,
  [PRAXISID] varchar(3) ,
  [KVKLESEPORT] varchar(1) ,
  [PAINPUTORDER] varchar(1) ,
  [LOGINPID] varchar(3) ,
  [PROGPATH] varchar(64) ,
  [STDKFOPLANVORLAGEK] varchar(3) ,
  [STDKFOPLANVORLAGEP] varchar(3) ,
  [QAMDID] varchar(2) ,
  [QASTART] varchar(8) ,
  [QAKFO] varchar(1) ,
  [LQSORT] varchar(1) ,
  [LQIGNOREDELAY] varchar(2) ,
  [PHLEBID] varchar(3) ,
  [PHPLANUNGSTART] varchar(8) ,
  [PHPLANUNGEND] varchar(8) ,
  [PHEINGLIEDERUNGSTART] varchar(8) ,
  [PHEINGLIEDERUNGEND] varchar(8) ,
  [PHPLANART] varchar(1) ,
  [PHPLANSTATUS] varchar(1) ,
  [ACTPATNR] varchar(10) ,
  [FAKTVONDATUM] varchar(8) ,
  [FAKTBISDATUM] varchar(8) ,
  [FAKTSORT] varchar(1) ,
  [FAKTRART] varchar(4) ,
  [FAKTKTRAEGER] varchar(1) ,
  [FAKTLAENGERALS] varchar(2) ,
  [FAKTGROESSERALS] varchar(10) ,
  [CASHVONDATUM] varchar(8) ,
  [CASHBISDATUM] varchar(8) ,
  [CASHSORT] varchar(1) ,
  [CASHBART] varchar(1) ,
  [CASHZWEG] varchar(1) ,
  [FAKTASKSTORNODRUCK] varchar(1) ,
  [BEHPAR] varchar(80) ,
  [AKTIV] varchar(1) ,
  [PROGAKTIV] varchar(20) ,
  CONSTRAINT [PK_WORKSTATION] PRIMARY KEY ([LFDWORKSTATION])
);

CREATE TABLE [WORKSTEP] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LFDWORKFLOW] varchar(3) ,
  [LFDWORKSTEP] varchar(2) ,
  [WORKSTEPART] varchar(3) ,
  [WORKSTEPSTATUS] varchar(1) ,
  [PID] varchar(3) ,
  [ERLEDIGTPID] varchar(3) ,
  [ZEITSTEMPEL] varchar(14) ,
  [BEMERKUNG] varchar(60) ,
  [PRIO] varchar(1) ,
  CONSTRAINT [PK_WORKSTEP] PRIMARY KEY ([PATNR], [LFDWORKFLOW], [LFDWORKSTEP])
);

CREATE TABLE [WSFAVORIT] (
  [RINFO] varchar(34) ,
  [WORKSTATION] varchar(3) ,
  [PROGID] varchar(3) ,
  [PID] varchar(3) ,
  [CHECKIN] varchar(17) ,
  [FAVORIT] varchar(254) ,
  [LASTCHECKIN] varchar(17) ,
  [ANZCALLS] varchar(9) ,
  [ANZSEKUNDEN] varchar(9) ,
  [TESTMODUS] varchar(1) ,
  [PROTOKOLLDATEI] varchar(20) ,
  [RESULTS] varchar(40) ,
  CONSTRAINT [PK_WSFAVORIT] PRIMARY KEY ([WORKSTATION], [PROGID])
);

CREATE TABLE [Z1KASSEN] (
  [RINFO] varchar(34) ,
  [Z1KASKUERZEL] varchar(10) ,
  [KYZ1KASKUERZEL] varchar(10) ,
  [ABDATUM] varchar(8) ,
  [ADRID] varchar(6) ,
  [GKVKAS] varchar(1) ,
  [MEDGO] varchar(1) ,
  [PWGROUP] varchar(10) ,
  [KVKSTATUS] varchar(1) ,
  [INBKV] varchar(1) ,
  [BKVKASNR] varchar(12) ,
  [INBKT] varchar(1) ,
  [BKTKASNR] varchar(11) ,
  [KASSENART] varchar(1) ,
  [KASSENBLOCK] varchar(1) ,
  [LARTABR] varchar(8) ,
  [BKVKASNAME] varchar(30) ,
  [KYBKVKASNAME] varchar(30) ,
  [PLZ] varchar(6) ,
  [ORT] varchar(30) ,
  [STR] varchar(30) ,
  [TELEFON] varchar(16) ,
  [TELEFAX] varchar(16) ,
  [VKNR] varchar(5) ,
  [FUSIONSVKNR] varchar(5) ,
  [BKTKASSENART] varchar(2) ,
  [AUSSCHLUSSKV] varchar(60) ,
  [BKTVKNRGUELTIGBIS] varchar(8) ,
  [BKTVKNRGUELTIGAB] varchar(8) ,
  [KVKKASNRGUELTIGBIS] varchar(8) ,
  [KVKKASNRGUELTIGAB] varchar(8) ,
  [BKTABKGUELTIGBIS] varchar(8) ,
  [BKTABKGUELTIGAB] varchar(8) ,
  [BKTKASNAME] varchar(30) ,
  [BKTPLZ] varchar(8) ,
  [BKTORT] varchar(30) ,
  [BKTSTR] varchar(60) ,
  [BKTPLZ2] varchar(8) ,
  [BKTORT2] varchar(30) ,
  [BKTPOSTFACH] varchar(60) ,
  [LASTBKVABGLEICHDATUM] varchar(8) ,
  [LASTBKTABGLEICHDATUM] varchar(8) ,
  [STATISTIKSPALTE] varchar(1) ,
  [MEDSTATISTIKSPALTE] varchar(1) ,
  [HVMBUDGET] varchar(1) ,
  [PRIVLIQSPEZDIAG] varchar(1) ,
  [PRIVLIQSPEZFAKTOR] varchar(18) ,
  [KFOFALLPAUSCHLSTNR] varchar(6) ,
  [EBZIK] varchar(9) ,
  CONSTRAINT [PK_Z1KASSEN] PRIMARY KEY ([KYZ1KASKUERZEL], [ABDATUM])
);
CREATE INDEX [K2Z1KASSEN] ON [Z1KASSEN] ([KYBKVKASNAME]);

CREATE TABLE [Z1POST] (
  [RINFO] varchar(34) ,
  [LANDKUERZEL] varchar(3) ,
  [KYLANDKUERZEL] varchar(3) ,
  [PLZ] varchar(20) ,
  [KYPLZ] varchar(20) ,
  [ORT] varchar(50) ,
  [KYORT] varchar(50) ,
  [STR] varchar(50) ,
  [KYSTR] varchar(50) ,
  [HAUSNRRANGE] varchar(30) ,
  [KYHAUSNRRANGE] varchar(30) ,
  [LANDVORWAHL] varchar(20) ,
  [VORWAHL] varchar(20) ,
  [KYVORWAHL] varchar(20) ,
  CONSTRAINT [PK_Z1POST] PRIMARY KEY ([KYLANDKUERZEL], [KYPLZ], [KYORT], [KYSTR], [KYHAUSNRRANGE])
);
CREATE INDEX [K2Z1POST] ON [Z1POST] ([KYORT], [KYSTR]);
CREATE INDEX [K3Z1POST] ON [Z1POST] ([KYLANDKUERZEL], [KYPLZ], [KYSTR]);
CREATE INDEX [K4Z1POST] ON [Z1POST] ([KYVORWAHL]);

CREATE TABLE [Z1SYSTEM] (
  [RINFO] varchar(34) ,
  [Z1SYSTEMID] varchar(1) ,
  [STAMMLEBLIQ] varchar(1) ,
  [VSPID] varchar(2) ,
  [KUNDENNR] varchar(8) ,
  [LANDKUERZEL] varchar(3) ,
  [LANDSPRACHE] varchar(4) ,
  [DBRELEASE] varchar(3) ,
  [UPDATUM] varchar(8) ,
  [VITAXDATEN] varchar(254) ,
  CONSTRAINT [PK_Z1SYSTEM] PRIMARY KEY ([Z1SYSTEMID])
);

CREATE TABLE [ZBON] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [DATUM] varchar(8) ,
  [KBKTO] varchar(6) ,
  [LFDZBON] varchar(6) ,
  [ZEIT] varchar(4) ,
  [INFO] varchar(40) ,
  CONSTRAINT [PK_ZBON] PRIMARY KEY ([MDID], [DATUM], [KBKTO])
);

CREATE TABLE [ZEHIT] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [PATNR] varchar(10) ,
  [LFDPATBILL] varchar(5) ,
  [ABRART] varchar(1) ,
  [ABRPERDTA] varchar(1) ,
  [GLFDPATVD] varchar(3) ,
  [GKTRAEGER] varchar(1) ,
  [PLFDPATVD] varchar(3) ,
  [PKTRAEGER] varchar(1) ,
  [BILLELSE] varchar(80) ,
  [LFDPLAN] varchar(3) ,
  [PLANUNGSDATUM] varchar(8) ,
  [GUTACHTERDATUM] varchar(8) ,
  [GENEHMIGUNGSDATUM] varchar(8) ,
  [EINGLIEDERUNGSDATUM] varchar(8) ,
  [DTADATUM] varchar(8) ,
  [PRUEFCODE] varchar(3) ,
  [ABRSTATUS] varchar(1) ,
  [PATTITEL] varchar(28) ,
  [PATVORNAME] varchar(28) ,
  [KYPATVORNAME] varchar(28) ,
  [PATAPPENDIX] varchar(15) ,
  [PATNAME] varchar(28) ,
  [KYPATNAME] varchar(28) ,
  [PATSTRASSE] varchar(30) ,
  [PATWLC] varchar(3) ,
  [PATPLZ] varchar(7) ,
  [PATORT] varchar(30) ,
  [PATGEBDATUM] varchar(8) ,
  [BKVNR] varchar(12) ,
  [BKVKASNAME] varchar(30) ,
  [MFRDIG] varchar(1) ,
  [RSA] varchar(3) ,
  [WSO] varchar(1) ,
  [VERSICHERTENNR] varchar(12) ,
  [KZVINTERN] varchar(254) ,
  [UNFVSINTIMUNBROKUK] varchar(10) ,
  [ALTERCA] varchar(2) ,
  [BEFUND1] varchar(32) ,
  [BEFUND2] varchar(32) ,
  [PLANUNG] varchar(32) ,
  [VERBLENDUNG] varchar(32) ,
  [HALTEELEMENT] varchar(32) ,
  [VERBINDUNG] varchar(32) ,
  [VERBLOCKUNG] varchar(32) ,
  [DTABEMERKUNG] varchar(254) ,
  [VBPUNKTSUMPFG] varchar(10) ,
  [NBPUNKTSUMPFG] varchar(10) ,
  [PWZE] varchar(9) ,
  [KASSENANTEIL] varchar(3) ,
  [MLGESCHAETZTPFG] varchar(10) ,
  [FLABPFG] varchar(10) ,
  [ELABPFG] varchar(10) ,
  [ANZPORTO] varchar(2) ,
  [SUMPORTOPFG] varchar(10) ,
  [METKOSTENOMWST] varchar(10) ,
  [ANZKRONEN] varchar(2) ,
  [ZUSCHPROKRONE] varchar(7) ,
  [KASANTGOLDPFG] varchar(10) ,
  [ZE1] varchar(80) ,
  [ZE2] varchar(80) ,
  [ZE3] varchar(80) ,
  [ZE5] varchar(254) ,
  [ZE4] varchar(254) ,
  [KZVINTERN2] varchar(254) ,
  [ANTRAGSNUMMER] varchar(80) ,
  CONSTRAINT [PK_ZEHIT] PRIMARY KEY ([MDID], [PATNR], [LFDPLAN])
);
CREATE UNIQUE INDEX [K2ZEHIT] ON [ZEHIT] ([MDID], [KYPATNAME], [KYPATVORNAME], [PATGEBDATUM], [PATNR], [LFDPLAN]);
CREATE UNIQUE INDEX [K3ZEHIT] ON [ZEHIT] ([MDID], [DTADATUM], [KYPATNAME], [KYPATVORNAME], [PATGEBDATUM], [PATNR], [LFDPLAN]);

CREATE TABLE [ZEHITLST] (
  [RINFO] varchar(34) ,
  [MDID] varchar(2) ,
  [PATNR] varchar(10) ,
  [LFDPLAN] varchar(3) ,
  [LFDLST] varchar(3) ,
  [PRUEFCODE] varchar(3) ,
  [NACHTRAEGLICH] varchar(1) ,
  [GOART] varchar(1) ,
  [LSTNR] varchar(6) ,
  [DRUCKBILD] varchar(6) ,
  [ANZAHL] varchar(6) ,
  [LST1] varchar(80) ,
  [LST2] varchar(80) ,
  CONSTRAINT [PK_ZEHITLST] PRIMARY KEY ([MDID], [PATNR], [LFDPLAN], [LFDLST])
);

CREATE TABLE [ZPLAN] (
  [RINFO] varchar(34) ,
  [PATNR] varchar(10) ,
  [LFDPLAN] varchar(3) ,
  [LEBID] varchar(3) ,
  [LFDAPLAN] varchar(3) ,
  [BEFUNDART] varchar(1) ,
  [LFDBEFUND] varchar(3) ,
  [PLANART] varchar(1) ,
  [KASSENPLAN] varchar(1) ,
  [MUSTER] varchar(1) ,
  [PAUSCHVERTRAGSART] varchar(1) ,
  [PLANUNGSDATUM] varchar(8) ,
  [PWGEMPLANUNGSDATUM] varchar(1) ,
  [KASGEMPLANUNGSDATUM] varchar(1) ,
  [DRUCKDATUM] varchar(8) ,
  [GUTACHTERDATUM] varchar(8) ,
  [GUTACHTERADRID] varchar(6) ,
  [GENEHMIGUNGSDATUM] varchar(8) ,
  [ENDDATUM] varchar(8) ,
  [KZVABRDATUM] varchar(8) ,
  [KZVEINREICHDATUM] varchar(8) ,
  [AKZEPTIERTDATUM] varchar(8) ,
  [PLANSTATUS] varchar(1) ,
  [PLANUNGSPID] varchar(3) ,
  [ABRECHNUNGSPID] varchar(3) ,
  [MACID1O] varchar(216) ,
  [MACID1U] varchar(216) ,
  [OVERRULED1] varchar(72) ,
  [MACID2O] varchar(216) ,
  [MACID2U] varchar(216) ,
  [OVERRULED2] varchar(72) ,
  [WEDERPALLNOCHNEM] varchar(1) ,
  [UNFALL] varchar(1) ,
  [VERSORGUNGSLEIDEN] varchar(1) ,
  [INTERIMSVERSORGUNG] varchar(1) ,
  [UNBRAUCHBAREPROTHESE] varchar(1) ,
  [IMMEDIATVERSORGUNG] varchar(1) ,
  [REPEINZELKRONEN] varchar(1) ,
  [REPWIEDERHERSTELLUNG] varchar(1) ,
  [REPOBERKIEFER] varchar(1) ,
  [REPUNTERKIEFER] varchar(1) ,
  [REPIMVORAUSMOEGLICH] varchar(1) ,
  [ROENTGENDIAGNOSTIK] varchar(1) ,
  [ANZKRONEN] varchar(2) ,
  [ALTERCA] varchar(2) ,
  [BEMERKUNG1] varchar(40) ,
  [BEMERKUNG2] varchar(40) ,
  [BEMERKUNG3] varchar(40) ,
  [BEMERKUNG4] varchar(40) ,
  [METKOSTENOMWST] varchar(10) ,
  [ZUSCHPROKRONE] varchar(7) ,
  [ABRPUNKTWERT] varchar(9) ,
  [KASSENANTEIL] varchar(3) ,
  [ANTRAGSNUMMER] varchar(80) ,
  [MITTEILUNGSNUMMER] varchar(80) ,
  [PLANSONST1] varchar(254) ,
  [DEAKTIVIERTDATUM] varchar(8) ,
  [BEMERKUNG5] varchar(150) ,
  [UPTALTPLAN] varchar(254) ,
  [BEMERKUNG6] varchar(150) ,
  [ANAMNESE] varchar(254) ,
  [BEHANDLUNGVORGESEHEN] varchar(254) ,
  CONSTRAINT [PK_ZPLAN] PRIMARY KEY ([PATNR], [LFDPLAN])
);
CREATE UNIQUE INDEX [K2ZPLAN] ON [ZPLAN] ([LEBID], [PATNR], [LFDPLAN]);

